librespot-org/librespot

- src/audio_backend/pulseaudio.rs
Added Fork from Ipha to start stop the sink
> Stop pulseaudio sink when not in use

- src/spirc.rs
> Added repeat and shuffle support from kingosticks 

- src/discovery.rs
- src/main.rs
Added zeroconf-port option. Will merge in a few hours unless there are corrections/objections.
> Add zeroconf-port option

- src/main.rs
Cleaned up the initial-volume code. I've changed it so that if there is a number outside 0-100 it will be set at 50% and show a debug message.
> Initial volume ifelse cleanup

- Cargo.toml
- src/audio_backend/jackaudio.rs
- src/audio_backend/mod.rs
- src/lib.rs
PR continuation from https://github.com/librespot-org/librespot/pull/115, as previous branch was read only.
> Jackaudio Support

- src/spirc.rs
My original PR at https://github.com/librespot-org/librespot/pull/119 got all screwed up when I changed my fork from plietar/librespot to librespot-org/librespot. So here it is again.
1) A queued track is removed once it has become the current track.
Note that the track doesn't need to actually play i.e. it could
have been immediately skipped over with `next()`. This is
implemented in `consume_queued_track()`.
2) Queued tracks are always positioned immediately after the current
track. 1) ensures this is true for `next()` but `prev()` requires
all the queued tracks are actually moved for this to remain the
case.
Also fixed the case where `prev()` on the first track would incorrectly
wrap back around to the last track even when repeat was disabled. The
correct behaviour is to remain on the …
> Improved next/prev handling for queued tracks. (v2)

- .gitignore
- discovery/src/discovery.rs
- src/main.rs
This PR replaces pull request #111.
> Rustify some recent changes according to plietar

- Cargo.lock
- core/Cargo.toml
- core/build.rs
- core/src/connection/handshake.rs
- core/src/connection/mod.rs
- core/src/lib.in.rs
- core/src/lib.rs
Addresses #129 
@plietar please review
Once this is done I will do the same to connect.
> core: remove protobuf_macros

- connect/src/spirc.rs
- core/src/authentication.rs
- core/src/spotify_id.rs
- examples/play.rs
- metadata/src/lib.rs
- src/main.rs
Last couple of bits to do. I assumed the ```get_credentials``` task was a request to move the password reading logic into a seperate function. 
SpotifyId methods now return ```Result```, code has been updated and tested.
Have not added the to_raw or from_raw methods to FileId as I'm not sure what the point of doing so is, nor am I familiar with the format of the FileId or what it's used for, and hence will leave that to someone else to do, if even necessary to add.
@plietar this should wrap up #130 as far as I can tell. Are you ok to give the code in the repo a final once over, and if all is good, package it and publish to crates.io?
> API review

- README.md
This is just bound to become out of date, and is what GH issues are for.
> Remove TODO list from README

- examples/play.rs
Fixed the player initializing in the example play.rs #201
> Fixes player initialization in the play.rs

- src/main.rs
see remarks by @plietar on #212
> reverse #212 since it does not address the real problem

- playback/src/audio_backend/jackaudio.rs
> Fixed Jackaudio compiling

- .dockerignore
- contrib/Dockerfile.Rpi
A docker file to create an image which can be directly run on an RPI.
> Docker file to create an RPI image

- src/player_event_handler.rs
> Changed TRACK_ID from base16 to base62 so that it is equal with the official Spotify app

- audio/src/fetch.rs
Closes #250 thanks @ashthespy. If others could test this on any tracks that are known to be problematic, that would be good, will leave this here for a couple of days before merging.
> Fix seek past EOF panic for some tracks

- README.md
This PR adds `ncspot` to the list of related projects. Thanks for your hard work!
> Add ncspot to list of related projects

- connect/src/spirc.rs
- core/src/session.rs
With my poor Rust skills I should have fixed the issue faced in #310
> Fix for time alignment issue

- connect/src/spirc.rs
- core/src/session.rs
> Server time delta is a signed integer

- Cargo.lock
- Cargo.toml
- playback/Cargo.toml
- playback/src/audio_backend/mod.rs
- playback/src/audio_backend/sdl.rs
- playback/src/lib.rs
> add SDL backend based on sdl2 crate

- connect/src/spirc.rs
Follow up from https://github.com/librespot-org/librespot/pull/305#pullrequestreview-214843475
Had some time to read the docs again, this *should* be a cleaner implementation.
I am still unsure if this mimics the official clients - my windows client sometimes seems to update the queue on the fly for my Dailymixes, even before resolving the new tracks. ¯\\_(ツ)_/¯
> Refactor adding context tracks to state

- .travis.yml
Hopefully have all the right dependencies.
> Add all backends to Travis

- README.md
> Fixed slight typo

- examples/play.rs
- src/lib.rs
- src/main.rs
Reverts 34317ec and reinstates 4e0d470
> Revert "Fix play.rs example"

- contrib/Dockerfile
Fixes #389
Seemed to have missed pushing this following https://github.com/librespot-org/librespot/pull/245#issuecomment-430247445.
> Add `pkg-config` to docker build container

- Cargo.lock
- connect/Cargo.toml
Minor update that should re-fix https://github.com/librespot-org/librespot/issues/75
> libmdns 0.2.4

- connect/src/spirc.rs
- core/src/config.rs
- src/main.rs
Fixes #294 
Not the most elegant approach, but should work.
> Autoplay similar songs when your music ends

- connect/src/spirc.rs
For example from Liked Songs (`spotify:user:xxx:collection`)
Fixes #420
> Don't panic when no autoplay uri is obtained

- protocol/Cargo.toml
> Pin protobuf versions to allow patch updates only

- Cargo.lock
- connect/Cargo.toml
- src/main.rs
Bumped up `libmdns` to `0.2.5` and fix some logging stragglers 
Fixes #454
PS: @willstott101 quick tag to confirm
> libmdns housekeeping

- connect/src/spirc.rs
This pull request implements the fix suggested by @Johannesd3 in his comments against Issue #497
> Issue #497 - Playing songs from android app

- README.md
You don't "offer the a selection of audio backends", you "offer the following selection of audio backends".
> Simple grammar fix

- .github/workflows/test.yml
Tests currently fail with some apt error:
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
This change would add the suggested `apt-get update`
> Attempt to fix tests

- playback/src/config.rs
- playback/src/player.rs
- src/main.rs
Add option to choose between track or album normalisation gain, set default normalisation gain type to album. If there's something I've missed here, let me know.
> Add option to choose between track or album normalisation gain

- .github/workflows/test.yml
This should hopefully cache build dependencies and speed up CI testing.
> Cache build dependencies in Github Workflows

- Cargo.lock
- connect/Cargo.toml
Dunno if this PR is the right thing to do, but this is a pretty trivial change tbh and we might as well get this support stabilised in.
> Stabilises #529 (NetBSD support)

- README.md
- connect/src/discovery.rs
- connect/src/spirc.rs
- core/src/channel.rs
- core/src/connection/handshake.rs
- metadata/src/lib.rs
- playback/src/mixer/mod.rs
- playback/src/player.rs
- src/main.rs
Fix the remaining clippy warnings and some other small improvements. Nothing spectacular.
> Fix remaining clippy warnings

- audio/src/fetch/mod.rs
- audio/src/fetch/receive.rs
e71a004e93d9376bb30834416cdd9248ad521246 broke the streaming mode, this PR fixes my mistake.
> Fix broken streaming mode

- core/src/channel.rs
- core/src/mercury/mod.rs
- core/src/session.rs
I just realized this macro exists. In conjunction with the `?` operator it makes a lot of boilerplate `match` expressions redundant.
> Use `ready!` macro to reduce boilerplate

- connect/src/spirc.rs
Reverts librespot-org/librespot#666
> Revert "Add shuffle command and command handling"

- .github/workflows/test.yml
Some minor fixes of the github workflow.
> Fix workflow

- CHANGELOG.md
- playback/src/config.rs
- playback/src/player.rs
- src/main.rs
> Fix default normalisation threshold

- core/src/mercury/sender.rs
There was a bug in `MercurySender`. This bug did not have any consequences, since the requests were executed nevertheless, and just the channel for the response was dropped too early (but no one was interested in these responses).
> Fix bug in MercurySender

- Cargo.lock
- playback/Cargo.toml
jack 0.7.0 -> 0.7.1
Rodio 0.13.1 -> 0.14.0
Playback verified so I'll merge this if CI is successful.
> Bump jack and Rodio crates

- core/src/dealer/mod.rs
- core/src/dealer/protocol.rs
* Added sleep before next reconnection try.
* Use constants for durations.
* Removed generic parameter of message and request, which were a relict of gzip support.
* Implement `Error` for the errors.
> Mostly cosmetic changes in `dealer`

- core/src/spotify_id.rs
> Fix integer overflow in spotify_id

- CHANGELOG.md
- playback/src/audio_backend/alsa.rs
As discussed in https://github.com/librespot-org/librespot/discussions/788 this I believe is a better implementation.
This is ofc a wip and I look forward to any help as far as making it more rust like as this is my 1st attempt at writing rust.
When everything is squared away I will write a more meaningful commit message.
> Improve ALSA buffer size

- playback/src/audio_backend/alsa.rs
Fix the clippy warnings caused by https://github.com/librespot-org/librespot/pull/797
> Fix clippy warnings

- .github/workflows/test.yml
Make CI ignore things that should not trigger build tests.
> Make CI ignore things that should not trigger build tests

- CONTRIBUTING.md
- README.md
Also, define when a change is "breaking".
> Fix documentation typos

- CHANGELOG.md
- metadata/src/lib.rs
> metadata: avoid unwrapping when parsing a playlist

- playback/src/audio_backend/alsa.rs
Dynamically set the alsa buffer and period based on the device's reported min/max buffer and period sizes. In the event of failure use the device's defaults.
This should have no effect on devices that allow for reasonable buffer and period sizes but would allow us to be more forgiving with less reasonable devices or configurations.
Closes: https://github.com/librespot-org/librespot/issues/895
> Dynamic failable buffer sizing alsa-backend

- playback/src/player.rs
I haven't encountered this myself, but this should close #902.
> Skip track on decoding error

- playback/src/audio_backend/alsa.rs
Fix a typo and be a little more forgiving.
> Clean up list_compatible_devices

- playback/src/decoder/symphonia_decoder.rs
This change fixes the handling of the `ResetRequired` error. By propagating the `ResetRequired` error up, the next Spotify track will be advanced to. This should be perfectly acceptable behaviour for librespot.
This change also modifies the decode loop to skip corrupted packets when they're encountered. If the decode error is propagated up then the next track will be advanced to which seems undesirable.
I tested these changes with about 15 or so songs.
> Handle reset and decode errors with the Symphonia decoder.

- protocol/proto/connectivity.proto
Added linux fields to connectivity
> Add more connectivity.proto fields

- CHANGELOG.md
- playback/src/player.rs
Less math and logic that follows the spec.
> simplify get_factor

- CHANGELOG.md
- connect/src/spirc.rs
fixes https://github.com/librespot-org/librespot/issues/959
> Prevent shuffle crash

- .github/workflows/test.yml
- COMPILING.md
- Cargo.lock
- playback/Cargo.toml
- playback/src/audio_backend/gstreamer.rs
See individual commits for details.
Previous discussion here: https://github.com/librespot-org/librespot/pull/961
> Update to GStreamer bindings version 0.18 and various cleanups to the GStreamer audio backend

- playback/src/decoder/symphonia_decoder.rs
* Remove unwrap
* Refactor normalisation_data.
> symphonia_decoder tweak

- .github/workflows/test.yml
- CHANGELOG.md
- COMPILING.md
See: https://github.com/librespot-org/librespot/pull/997
> Bump MSRV to 1.53

- .github/workflows/test.yml
- CHANGELOG.md
- COMPILING.md
- Cargo.lock
- playback/Cargo.toml
- playback/src/audio_backend/alsa.rs
- playback/src/audio_backend/sdl.rs
Let's see if this will blow up or not?
> Update deps round 2

- CHANGELOG.md
- playback/src/mixer/alsamixer.rs
fixes https://github.com/librespot-org/librespot/issues/1008
> Fix fixed volume with hardware mixer.

- src/main.rs
Fixes https://github.com/librespot-org/librespot/issues/1011
> Fix --opt=value line argument logging

- playback/src/audio_backend/pipe.rs
* Implement stop
* Better error handling
> Improve pipe backend

- README.md
include a mention in the README of the snapcast project that uses librespot for Spotify sources
Thanks for this awesome library, guys!
> related project: snapcast

- Cargo.toml
- audio/Cargo.toml
- audio/src/range_set.rs
- connect/Cargo.toml
- connect/src/spirc.rs
- core/Cargo.toml
- core/src/config.rs
- core/src/file_id.rs
- core/src/lib.rs
- core/src/spotify_id.rs
- discovery/Cargo.toml
- metadata/Cargo.toml
- metadata/src/restriction.rs
- playback/Cargo.toml
- playback/src/audio_backend/mod.rs
- playback/src/player.rs
- protocol/Cargo.toml
- protocol/src/lib.rs
- rustfmt.toml
Anyone any objections against migrating to Rust 2021?
> Migrate to Rust 2021

- core/src/http_client.rs
- Keep using the same hyper client instead of building a new one for each request
- This allows the client to reuse connections and improves the performance of multiple requests by almost 2x
- The playlist_tracks example takes 38 secs before and 20 secs after the change to enumerate a 180 track playlist
- To avoid carrying the hyper Client generics through the whole project, `ProxyConnector` is always used as the Connector, but disabled when not using a proxy. This should have no real overhead
- The client creation is done lazily to keep the `HttpClient::new` without a `Result` return type
> Keep using the same hyper client

- core/src/token.rs
I noticed that there was a clippy lint warning (for code I didn't actually touch?) when my PR was merged. This should shut clippy up.
> Fix clippy lint

- discovery/examples/discovery.rs
From https://github.com/librespot-org/librespot/commit/05dcb652a0acba529a5674e00312fba2a8ef20e6
> Fix fmt lint

- core/src/connection/handshake.rs
rsa::padding::PaddingScheme is !Send, making it impossible to call Session::connect() with an executor requiring Send futures, such as Rocket.
Fix #1065
> core: workaround for Session::connect() future being !Send

- CHANGELOG.md
- core/src/spotify_id.rs
This adds support for parsing playlist URIs with named IDs.
> Parse playlist URIs with named IDs

- core/src/connection/handshake.rs
Hi, I've added changes which should fix the error reported in #1107 caused in the dev branch.
> Add back pow_response and crypto_response

- audio/src/fetch/receive.rs
- audio/src/range_set.rs
- core/build.rs
- core/src/apresolve.rs
- core/src/cache.rs
- core/src/mercury/mod.rs
- core/src/proxytunnel.rs
- core/src/spclient.rs
- metadata/src/request.rs
- playback/src/audio_backend/alsa.rs
- playback/src/audio_backend/gstreamer.rs
- playback/src/audio_backend/jackaudio.rs
- playback/src/audio_backend/portaudio.rs
- playback/src/audio_backend/pulseaudio.rs
- playback/src/audio_backend/rodio.rs
- playback/src/audio_backend/sdl.rs
- playback/src/decoder/passthrough_decoder.rs
- playback/src/decoder/symphonia_decoder.rs
- src/main.rs
As reported by clippy, variables can be used directly in the `format!` string.
> Fix newly reported clippy errors

- playback/src/player.rs
Read all the Normalisation Data in one shot to avoid 4 seperate reads.
> Read Normalisation Data in one go

- core/src/authentication.rs
- core/src/session.rs
- playback/src/audio_backend/jackaudio.rs
> do not overwrite unchanged cached Credentials (#1168)

- connect/src/spirc.rs
- core/src/spclient.rs
> fix clippy errors

- core/src/dealer/mod.rs
fix #1293 with fix [core/src/dealer/mod.rs](https://github.com/librespot-org/librespot/blob/8f9bec21d7a0d1e095039c1ff9ecd7c532d9e74e/core/src/dealer/mod.rs#L412)
> Update core/src/dealer/mod.rs fix tokio-tungstenite with ver 0.23

- playback/src/player.rs
- protocol/proto/media_manifest.proto
- protocol/proto/metadata.proto
Fix for 96kbps playback and podcasts episodes issue. See https://github.com/librespot-org/librespot/issues/1236
> Fix 96kbps playback issue (issues #1236)

- Cargo.toml
- audio/Cargo.toml
- connect/Cargo.toml
- core/Cargo.toml
- discovery/Cargo.toml
- metadata/Cargo.toml
- oauth/Cargo.toml
- playback/Cargo.toml
- protocol/Cargo.toml
Make it easier to check and update.
> Cargo: use rust-version from workspace

- connect/src/spirc.rs
- core/src/session.rs
Addresses https://github.com/librespot-org/librespot/pull/1416/files#r1885390278
This was the only place the method is used.
> Remove session_id clones

- .github/workflows/build.yml
- .github/workflows/cross-compile.yml
- .github/workflows/quality.yml
- COMPILING.md
- Cargo.lock
- Cargo.toml
- audio/Cargo.toml
- connect/Cargo.toml
- core/Cargo.toml
- core/src/http_client.rs
- discovery/Cargo.toml
- metadata/Cargo.toml
- oauth/Cargo.toml
- oauth/src/lib.rs
- playback/Cargo.toml
😞 now for real this time by actually pulling in a certificate store on rustls.
There's a difference between getting it to compile and getting it to work... now properly tested.
Going to merge this when the CI passes.
> fix: rustls-tls features to support certificate stores
