librespot-org/librespot

Cargo.lock
README.md
core/src/config.rs
src/main.rs
src/spirc.rs

You can set initial volume to a value in [0-100]. 
e.g. 
`target/release/librespot --name DEVICENAME --initial-volume 40`
If not present the default volume will be 50% instead of 100%. IMO this allows user to have a better control: you can turn up and down the volume (before you can only turn it down).

Default volume 50% and --initial-volume argument

---

Cargo.lock
Cargo.toml
core/src/lib.in.rs
src/audio_backend/pulseaudio.rs
src/lib.in.rs
src/lib.rs
src/player.rs

When using librespot with pulseaudio over TCP, connection failures always lead to panics. This patchset introduces proper error handling in the pulseaudio backend and ensures that no undefined behaviour occurs in the FFI calls to pulseaudio. It also introduces proper error handling in the player thread: When the player fails to open or write audio, instead of panicking, it tries to reconnect to the sink every 5 seconds until it succeeds or playback is stopped.
With this patchset, librespot has been very reliable when running with pulseaudio and setting PULSE_SERVER to a remote host, even when the remote host goes down and comes up again.

Make librespot more robust against audio failures

---

.travis.yml
Cargo.lock
Cargo.toml
README.md
audio/src/fetch.rs
core/Cargo.toml
core/build.rs
core/src/audio_key.rs
core/src/channel.rs
core/src/connection/codec.rs
core/src/connection/handshake.rs
core/src/connection/mod.rs
core/src/lib.rs
core/src/mercury/mod.rs
core/src/session.rs
core/src/util/spotify_id.rs
metadata/src/lib.rs
src/discovery.rs
src/keymaster.rs
src/lib.rs
src/main.rs
src/player.rs
src/spirc.rs

librespot uses outdated versions of futures and tokio. It also uses deprecated functionality from those crates. This patch series modernizes the code base and removes all use of deprecated functions and types.

Update dependencies and fix the use of deprecated functionality

---

README.md

This is just a simple update to the readme to reflect this repo's intention as the replacement repo for plietar/librespot, and adds a to-do list for feature requests/problems that need resolving.

Proposed update to Readme.

---

Cargo.lock
Cargo.toml
src/discovery.rs
src/lib.rs

Code for allowing one to use dns-sd instead of mdns with the ```--features "dns-sd"``` compile time flag. Documentation needs to be added. Review and suggestions welcomed.

Feature flag for selecting dns service

---

metadata/src/lib.rs

Expose the track duration (in ms) as well in the metadata implementation.

Add track duration to `Track` metadata

---

.travis.yml
Cargo.lock
README.md
audio/Cargo.toml
audio/src/lewton_decoder.rs

This fixes #88 
I could not find a way to distinguish `NoCapturePatternFound` without adding `ogg`

lewton: handle OggError(NoCapturePatternFound)

---

.travis.yml
Cargo.lock
Cargo.toml
README.md
audio/Cargo.toml
audio/src/lewton_decoder.rs
audio/src/lib.rs

Switch `lewton_decoder` as default and `libvorbis_decoder` as optional after #123
Works fine here

lewton_decoder as default, libvorbis_decoder as optional

---

Cargo.toml
audio/Cargo.toml
connect/Cargo.toml
core/Cargo.toml

Option 5 from #128, usea  replace tag to switch to avx2 branch from [awmath/rust-crypto](https://github.com/awmath/rust-crypto/tree/avx2)

Implement [Replace] for rust-crypto

---

Cargo.lock
src/main.rs

Enables a full backtrace on all builds. Will merge in a couple of hours if no objections.

Enable backtrace on all builds

---

.travis.yml

This will prevent `Cargo.lock` from getting out of sync

travis: Use `cargo --locked` everywhere

---

Cargo.lock
core/src/connection/mod.rs

Adds an error! message informing of either incorrect password or free account before panicking. Are we satisfied that this is good enough to close #108?

Add error message to auth failure case

---

examples/play.rs

Updates paths that changed. This fixes the build: `cargo build --example play`

Fix example use declarations

---

connect/src/spirc.rs

Some more low-hanging fruit but useful for other things. It also allows remote clients to show the green now-playing indication (#57).

Include updating context_uri along with tracks and current index

---

Cargo.lock
playback/Cargo.toml
playback/src/config.rs
playback/src/lib.rs
playback/src/player.rs
src/main.rs

The heavy lifting was done by @herrernst. Since his PR has been quiet for a while, and there has been a significant reordering of librespot's structure, this is a reorder/rewrite, taking onboard feedback from #114. Review/suggestion welcomed. Closes #114

Add volume normalisation support

---

contrib/Dockerfile
contrib/docker-build-pi-armv6hf.sh

This is mainly from https://github.com/plietar/librespot/pull/202/ with a few changes.
mainly, moved the raspberrypi-tools/ download into the Dockerfile so that it can be cached.

Add a armv6hf crossbuild target

---

playback/src/audio_backend/pulseaudio.rs
playback/src/player.rs

Lewton returns empty packets from next_packet(). This caused problems with the pulseaudio backend.

Fix pulseaudio playback with Lewton

---

Cargo.lock
core/src/mercury/mod.rs

This is a lazy bandaid for the hanging issue when ```5xx``` errors occur. Librespot now panics when it encounters them, so at least supervisors can now relaunch it automatically.

Add 5xx error panic

---

src/main.rs

When we receive Ctrl-C we set shutdown to true, but we do not return from the Main Future with Ready without triggering Ctrl-C handler again.

return from Main loop on Ctrl-C/shutdown

---

connect/src/spirc.rs
core/src/cache.rs
core/src/config.rs
core/src/lib.rs
core/src/volume.rs
examples/play.rs
playback/src/audio_backend/jackaudio.rs
src/main.rs

This is a continuation of [https://github.com/librespot-org/librespot/pull/218](https://github.com/librespot-org/librespot/pull/218). Now, volume is cached when the user supplies the `--cache` directory. `--initial-volume` overrides cached volume, which in turn overrides the default hard-coded volume.
Currently, the volume is stored in a plaintext file containing only the (percentage) volume. In the future, it could be expanded into a config.json with other parameters as well, since I've largely copied the way that the credentials are stored in credentials.json.
I don't know if the final commit (passing to `Spirc` and `SpircTask`) is the most elegant way to access the cache from `volume_to_mixer`, so I'm open to any improvements to that aspect.

Cache volume across restarts

---

connect/src/spirc.rs

This fixes an issue loading new tracks probably caused by an update on spotify's side. The fix was suggested by @worleydl, all glory to them for figuring it out.
Resolves #288

Update subscription uri

---

core/src/connection/handshake.rs

That's it. Updating the version number in the `ClientHello` packet will unlock all the missing features.

Update version number

---

connect/src/discovery.rs
src/main.rs

This just handles this error situation more gracefully. I randomly made up the JSON result error codes/strings. 
There's also a couple of other tiny fixes.

Don't panic when the computed MAC doesn't match the client's expected MAC

---

connect/src/context.rs
connect/src/lib.rs
connect/src/spirc.rs

Fixes #57 #267 
While I managed to implement dynamic playlist support back in October, never opened up a PR as https://github.com/librespot-org/librespot/issues/57#issuecomment-446010775:
>Hmm because I couldn't find the proper mercury endpoint to give me that data in protobuf format. Currently it's in JSON and rather inelegant if you ask me.
Recent revelations from reverse engineering efforts by @devgianlu, @sashahilton00 show that we are going to have to bite the bullet and start sprinkling JSON into the mix.  
Playlist/Album/Track/Genre radios along with Dailymixes should all work. A point for discussion is on how the new tracks are added to the frame - should we at some point limit it?

Support for Spotify Radio/Dynamic Playlists

---

core/src/authentication.rs

`encoded_auth_blob` is used in the credentials response of the Facebook auth flow

Add credentials field alias

---

Cargo.lock
playback/Cargo.toml
playback/src/audio_backend/alsa.rs
playback/src/mixer/alsamixer.rs
playback/src/mixer/mod.rs
playback/src/mixer/softmixer.rs
src/main.rs

Following up from @joerg-krause's work from https://github.com/plietar/librespot/pull/160 (#45) 
Have finally found time to better understand (by just a little) the alsa hardware parameters  [(`snd_pcm_hw_params_t`)](http://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m___h_w___params.html) and get this working with the latest version of the `alsa-rs` crate.   
~~What remains to be done is passing the mixer/card/index parameters in. I currently cheat and use environment variables, but will polish it up based on what would work best.~~
Have exposed some new `mixer-name`, `mixer-card` and `mixer-index` run time flags. 
Also - let me know if you [see gaping holes in the arithmetic for the conversion](https://play.rust-lang.org/?gist=842a9c3ed89bd5e9a2a5c92f17573d9d&version=stable&mode=d …

Support for `alsa` mixer 

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/build.rs
core/src/version.rs

Since we are doing some general housekeeping anyway!
Not quite sure what `vergen` was doing as a build dependency for the binary though.  Looks to be a straggler from when the `librespot-core` was split out in https://github.com/librespot-org/librespot/issues/130?

Bump up vergen (and switch to rustc-env flags)

---

contrib/Dockerfile.Rpi

When cross-compiling using Dockerfile.Rpi I came across the following errors
```
...
Compiling c2-chacha v0.2.2
Compiling thread_local v0.3.6
Compiling lock_api v0.1.5
Compiling rustc_version v0.2.3
error: failed to run custom build command for `alsa-sys v0.1.2`
Caused by:
process didn't exit successfully: `/build/release/build/alsa-sys-9e3efef5874a428f/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
warning: build failed, waiting for other jobs to finish...
```
and 
```
....
Compiling crossbeam-utils v0.6.6
Compiling c2-chacha v0.2.2 …
```

add pkg-config and some configuration to Dockerfile.Rpi to allow cross-compilation

---

Cargo.lock
playback/Cargo.toml

`rodio` pushed a change (https://github.com/RustAudio/rodio/commit/0151398043a07e0b44583f03e77ad8ab935c3dbc) to, updating the dependency `cpal` to `v0.10`, which is incompatible with the current `librespot` implementation.
This wouldn't be noticeable when working with `librespot` directly based on how Cargo resolves dependencies (I think, still figuring this whole Rust thing out), but if `librespot` is being used as a dependency in another project, then the newer `cpal` crate also gets pulled in, and `librespot` won't compile.
The change in `rodio` has only occurred in the repository, there hasn't been a new version published, so I figured it would be better to pin the dependency version for the time being.

Lock Rodio to v0.9

---

.travis.yml

[Travis adds all build](https://docs.travis-ci.com/user/languages/rust/#dependency-management) artefacts to the cache, which gets quite big quite soon. 
Some googlefoo suggests that we can remove some of these to reduce the bloat. 
I also bumped up the number of concurrent builds, so each Rust version job should now run in parallel.

[Travis] Reduce cache bloat - don't save build artefacts

---

Cargo.lock
Cargo.toml

An effort to reduce binary sizes and compilation times.
Based on current HEAD (4a04e48f8a712f22feacfe61276b65d05bf775c8) and `rustc 1.38.0 (625451e37 2019-09-23)`
```
$ cargo build --release --no-default-features --features 'alsa-backend'
$ ls -la --block-size=k ./target/release/
-rwxrwxrwx 1 ash ash     4K Nov  6 14:32 liblibrespot.d
-rwxrwxrwx 2 ash ash    11K Nov  6 14:36 liblibrespot.rlib
-rwxrwxrwx 2 ash ash 13177K Nov  6 14:36 librespot
$ cargo build --release --no-default-features --features 'alsa-backend'
$ ls -la --block-size=k ./target/release/
-rwxrwxrwx 1 ash ash     4K Nov  6 14:32 liblibrespot.d
-rwxrwxrwx 2 ash ash    11K Nov  6 14:46 liblibrespot.rlib
-rwxrwxrwx 2 ash ash 11896K Nov  6 14:47 librespot
```

Disable `regex` feature of `env_logger`

---

audio/src/fetch.rs

I noticed some ocational buffer under-runs as a consequence of PR #393 for which I made a fix here.
The issue is, that the pre-fetch algorithm can potentially fire of lots of small requests to keep the amount of pending bytes at the desired level. If bandwidth limits are hit, this leads to responses being interleaved - all requests are served simultaneously, which means the total data rate is great but each single request experiences a low data rate. A consequence can be, that the first request isn't responded to in time and we get a buffer under-run.
I solved this by limiting the amount of open requests when pre-fetching: a pre-fetch request is only sent when less than 4 requests are open. This leads to less requests which are larger. Thus, individual requests should still get decent …

Limit number of requests for pre-fetching 

---

README.md

Hi this PR is a documentation-only change to mention the related rpi-audio-receiver project by @nicokaiser that makes it easy to install Spotifyd and other audio reveiver protocols onto Raspbian. Thanks for all your great work on librespot. ArtMG

readme related project rpi-audio-receiver

---

README.md

Minor changes to README, mainly link to discussion about libspotify being no more - the Spotify blog post about it is now gone, so linked to discussion on modify-spotify issue tracker instead.

Update readme regarding libspotify deprecation

---

connect/src/spirc.rs

I investigated a panic I observed. spirc's handle_next was called on an empty queue resulting in an index violation on the queue. I modified the code to catch this kind of situation.
Unfortunately I don't know how to reproduce this situation - I only saw it in the logs and we were mucking around with spotify quite a bit at the time so I don't know which of our actions caused it. Nevertheless I think it's worth fixing.

Prevent spirc from crashing when the queue is empty.

---

Cargo.lock
playback/Cargo.toml
playback/src/audio_backend/mod.rs
playback/src/audio_backend/subprocess.rs
playback/src/lib.rs

Added subprocess audio backend.
Simple test with ```ffmpeg``` installed:
```
cargo run -- -n "Librespot Speaker" -b 160 --backend subprocess --device "ffplay -i -  -f s16le -ac 2 -nodisp"
```
Also ```Sink``` is stopping and starting again after every track. Is there a way to prevent this behaviour?

Subprocess audio backend

---

connect/src/spirc.rs

Seems strange that these fields return true in the has_ methods when as far as I can tell it's impossible to remove the shuffle/repeat state in the client without explicitly toggling them with their dedicated buttons.
@devgianlu You mention in #266 that that librespot-java might handle this better, (I couldn't get it to work with Zeroconf on my windows laptop, I'll try again later), but [browsing the code](https://github.com/librespot-org/librespot-java/blob/0a08ba32eb8036f96a65f1cc57e1ea155da52ff1/core/src/main/java/xyz/gianlu/librespot/player/StateWrapper.java#L251) I couldn't see anything like this so I'm curious if the shuffle state does actually work better over there? Perhaps you've found a better solution.
EDIT: It would be great if a few people could try this out and see if they …

Ignore false shuffle/repeat when changing contexts to match Android behaviour (fixes: #266)

---

audio/src/fetch.rs
connect/src/spirc.rs
examples/play.rs
metadata/src/lib.rs
playback/src/player.rs
src/main.rs
src/player_event_handler.rs

This PR allows librespot to perform gapless playback (issue #21). As far as I can see it's working well, but given the extent of the changes, it requires a good amount of testing.
**Features of this PR so far:**
- Upgrade of plumbing between spirc and player.
- Gapless playback: pre-loading and keeping the sink open.
- Improve notifications to Spotify: while loading a track, the status kPlayStatusLoading is sent and while playing, the correct playback position is transmitted (after loading, seek and buffer under runs).
- More and more detailed player events are produced.
The reason for having "additional features" in this one PR is that the necessary changes to the plumbing between the player and spirc made them come out naturally.
**And now to the more technical details:**
One of the …

Gapless play and improved notifications

---

src/main.rs

Since port 80 is the default port for the HTTP protocol, `url.port()` returns `None`, causing an "invalid proxy" message.  Using `port_or_known_default()` will only return `None` if the both the port has been omitted and an unknown protocol has been specified.
You can verify this like so:
```
$ librespot --proxy http://1.2.3.4:80
thread 'main' panicked at 'Invalid proxy url, only urls on the format "http://host:port" are allowed: "http://1.2.3.4/"', src/main.rs:291:33
```

Allow use of HTTP proxies listening on port 80

---

core/src/util/mod.rs

Instead of aborting with an `attempt to add with overflow` error, wrap the sequence around so that it goes back to 0 once it has reached the maximum value for the integer type.  Fixes #437.
Everything that uses sequences seems to treat them as unique values for matching asynchronous responses back to requests, so having the sequence number wrap at some point long after the original response has been received should cause no problems.

Make sequences wrap around to avoid overflows

---

playback/src/config.rs
playback/src/player.rs
src/main.rs

Follow up to the work in #430, added a runtime flag for the feature. 
@kaymes  I didn't look at your implementation in detail - but from a [quick glance](https://github.com/ashthespy/librespot/blob/2935544be86c479a223f87d7a42ca22f0fe61d63/playback/src/player.rs#L1229-L1231)  this should suffice or will the sink continue to remain open?

Disable gapless playback via runtime flag

---

.travis.yml
CONTRIBUTING.md

This means there are 5 distinct travis jobs - delaying the nightly build as we're only allowed 4 parrallel. But I've also made nightly an allowed_fail and enabled fast_finish which means the over-all time-to-ci-result is at worst the same as before. We'll see formatting failures in under 2 minutes which is nice.

Only format with stable rustfmt

---

playback/src/audio_backend/pulseaudio.rs

Pass the device name to the pulseaudio backend if --device was specified.

Enable pulseaudio device names

---

src/main.rs

Using "softmixer" as a mixer backend does not work, contrary to the output of `--help`.

Adjust help output: Use "softvol" as name for SoftMixer

---

playback/src/player.rs
src/main.rs
src/player_event_handler.rs

This PR adds more metadata to the PlayerEvents. I also added some comments that explain which PlayerEvent is fired when.
More PlayerEvents are now exposed through the --onevent script and the additional meta data is made available through additional environment variables.
Currently the additional metadata that is being exported is the title of the current track and its length.
It would be nice to add the Artist and maybe the cover art URL as well but this requires loading of additional information from the server. At this stage I'm only making available what's already there. So that's half of #439. 
(Loading the Artist info shouldn't be too difficult, but there doesn't seem to be an interface for the cover art yet - at least I couldn't find it in the code or protobuf definition).
While …

Add more data to player events and fire more of them

---

connect/src/spirc.rs

Fixes #442
Adds the `spotify:user:xxx:collection` to the types we fetch context for.

Fetch context for Spotify Collection types as well

---

connect/src/spirc.rs

It seems like Spotify changed the way the app behaves for kPlayStatusLoading. When I wrote this code, I tested it quite a bit with the desktop client (Linux) and the Android app. The behaviour for kPlayStatusLoading was that the desktop client would grey out the progress bar and the Android app just ignored it.
My understanding of kPlayStatusLoading was that it should be sent while loading a track but not yet playing it, so that's what I programmed.
With the new behaviour of the app, it seems like my interpretation of kPlayStatusLoading was wrong because the way the app behaves is indeed annoying and doesn't make sense when loading a track. Maybe it is intended to be sent during the start-up phase of a user-controlled client. I don't know.
In any case, librespot should probably refrain …

Don't send kPlayStatusLoading.

---

Cargo.toml

This weekend I tried to generate a deb package of librespot using cargo-deb and ran into some minor problems. After two minor edits I got a working package :)

Update package.metadata.deb to modern standards

---

connect/src/spirc.rs
core/src/mercury/mod.rs
core/src/util/mod.rs

Adapted from snippet by @ashthespy in #257.
Fixes the following error:
```
[2020-05-10T20:21:06Z WARN  librespot_core::mercury] error 400 for uri hm://remote/user/±e^2πi/
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MercuryError', connect/src/spirc.rs:331:23
```

Fix utf username

---

playback/src/audio_backend/alsa.rs

Based on experience with the alsa pulse plugin and raspotify (Particularly I was looking into the problem described in dtcooper/raspotify#210) and a comparison with aplay (Which can be regarded as a reference implementation of alsa playback and did fine job using the pipe backend) I started looking into the alsa backend, because it was clear that something was wrong there.
By comparing hw_params used in librespot with those in aplay and also a brief look through aplay.c, I was able to come up with the following two improvements to buffering in the alsa backend:
1. Introduce a decent period size relative to the desired buffer. This reduces the load on the CPU because it increases the wakeup interval.
2. Only write to the pcm when a full period of data is available. This again increased …

Alsa backend better buffering

---

connect/src/spirc.rs
playback/src/player.rs

Restoring the previous behaviour of skipping unplayable tracks. 
Not tested the case when a unplayable track is at the end of a playlist though..
>
>Yeah, sorry; here's one example:
>- https://open.spotify.com/playlist/4HrLayxlfZuW8YNwuK1g41?si=6_9XTofvTSW1ry4IY-95eg
>- spotify:playlist:4HrLayxlfZuW8YNwuK1g41
>
>_Originally posted by @pachulo in https://github.com/balbuze/volumio-plugins/issues/266#issuecomment-622396906_
@kaymes Do you see any issues?

Skip unplayable tracks instead of stopping

---

playback/src/player.rs
src/main.rs
src/player_event_handler.rs

This is kind of the same feature as PR #448, but in a blocking fashion. I'm putting it up for discussion as an alternative approach.
It addresses the issue mentioned in #406.
If activated, librespot emits events before the sink is opened and after it is closed. The events are blocking in the sense that the player waits for the handler to complete. This allows to write a handler that frees the sink before librespot attempts to open it.
From an API side, this is implemented as a callback. If a callback is registered, the player executes it blockingly.
From a binary side if --emit-sink-events is set, the usual --onevent script is used and librespot waits for the script's completion.
For simplicity, the events after closing are blocking, too. To make them non-blocking would require some more …

Add blocking SinkActive|SinkInactive events

---

core/src/spotify_id.rs

Was possible to determine different types of `SpotifyId` referencing the `audio_type` to format the URI when referencing it but having to write a `match` every time is redundant.
Added function due to ability to call it inside of Spotifyd when setting env for callback commands on player event.

Ability to get the Spotify URI from a SpotifyId

---

connect/src/spirc.rs
core/src/config.rs
src/main.rs

This is a (long) overdue follow up to https://github.com/librespot-org/librespot/pull/286#issuecomment-509263437.
I have refactored the old `--linear-volume` flag to a more generic `--volume-ctrl` flag that takes the options of `[linear, log, fixed]`. It defaults as previously to `log`. 
What `fixed` does is disable the client side volume control, by setting `kVolumeSteps` to 0, so no volume events are passed to the client.
As usual, this will need a update of the wiki, and should be considered a "breaking change" when considering the versioning. 
Fixes #48, Closes #286

Refactor Volume control, allow for a fixed volume option

---

playback/src/mixer/alsamixer.rs
playback/src/mixer/mod.rs
src/main.rs

This implements a cubic mapping for hardware mixers similar to [`alsamixer`](https://linux.die.net/man/1/alsamixer)
>Volume Mapping
In alsamixer, the volume is mapped to a value that is more natural for a human ear. The mapping is designed so that the position in the interval is proportional to the volume as a human ear would perceive it, i.e. the position is the cubic root of the linear sample multiplication factor. For controls with a small range (24 dB or less), the mapping is linear in the dB values so that each step has the same size visually.
>
>Only for controls without dB information, a linear mapping of the hardware volume register values is used (this is the same algorithm as used in the old alsamixer). 
Cherry picked from my old branch and did some housekeeping. It should work, …

[alsa] Implement cubic mapping for hardware mixers

---

examples/get_token.rs

Something that gets asked quite often - so here goes!

Add an example to fetch a Spotify API token

---

Cargo.lock
connect/Cargo.toml

Finally 🎉 
This is because `get_if_addrs` which is a libmdns dep didn't support NetBSD. So we're switching to a more active fork (`if-addrs`), but it took a while to finish the switch cause I had to fix regressed windows & rust=1.40.0 support on that fork.

Bump libmdns to 0.2.7 hopefully fixes: #520

---

README.md

Many operating systems have already packaged librespot. Add some documentation about the availability of official packages. [Repology](https://repology.org/project/librespot/versions) provides a great overview and nice badges over the package status along with available versions.
This is what the badges look like:
[![Packaging status](https://repology.org/badge/vertical-allrepos/librespot.svg)](https://repology.org/project/librespot/versions)

Add documentation about official packages

---

connect/Cargo.toml
core/Cargo.toml
metadata/Cargo.toml
playback/Cargo.toml
protocol/Cargo.toml

It's very unhelpful to not have links to the repo from the crates.io pages of the sub-crates.
I also threw in a trivial formatting fix.

Fix missing repo links in sub-crates

---

playback/src/player.rs
src/player_event_handler.rs

Hi,
I'm building a display for my sytsem running librespot and want to show the cover of the current track.
For this, I'm using the `onevent` option.
To minimize the delay between the track change and the cover being displayed, I need to preload the next cover picture.
I've added a new `Preloading` event that is triggered when librespot starts its own preload.
Please let me know if there's anything that needs to be fixed or improved.

Add a preload event to warn about new track coming soon

---

core/src/cache.rs

Automatically clean the audio cache when we encounter an error writing some file to the cache. Useful when used on a small target like the Pi or using the RAM as audio cache, which might get full quickly, especially if the Raspberry is always on

Handle cache full situation

---

Cargo.lock
playback/Cargo.toml
playback/src/audio_backend/pulseaudio.rs
playback/src/lib.rs

Hi, I'm not actually a librespot user, I just ended up here from noticing the dependency on such an old version of `libpulse_sys` and found myself working on fixing it...
This PR:
- Bundles a trivial fix for instances of conditional compilation incorrectly using crate names instead of feature names.
- Bumps the `libpulse_sys` dependency from v0.0.0 to v1.11+, which necessitates addition of `libpulse-simple_sys` since the 'simple' components were moved to their own crate (following the one crate per system library rule). This addresses the licensing issue mentioned in issue #539 with respect to this dependency.
- Rewrites the PulseAudio backend code to use the higher-level `libpulse-binding` and `libpulse-simple-binding` crates (v2.13+), rather than the raw 'sys' layer crates, resulting in …

Improve PulseAudio backend

---

COMPILING.md

such that it is readable as a text file, not only in "rendered" markdown
form on the web.

compiling.md: fixup table formatting

---

.github/workflows/test.yml
COMPILING.md
README.md

Fixes: #428
I converted my own crates earlier today and being on a roll I took care of this for you too.
Example successful run (before I tidied up the final commits):
https://github.com/jnqnfe/librespot/actions/runs/422461988
Not done:
- The caching stuff.
- The webhook notifications, since I could not find a solution.
- The `fast_finish` setting. There's a `fail-fast` setting which I've used, but this does not seem to do what `fast_finish` does.
I believe otherwise it's essentially equivalent.

CI: Replace Travis with Github Actions

---

core/src/cache.rs
src/main.rs

Cache split for system files (credentials and volume) and audio files. Retro-compatible by making the system cache the same as the audio cache if the option is not specified.
I kept the same directory tree for the audio cache by keeping the `files` directory, might not be needed. 
Use case for this new option : splitting the cache into two : audio cache in a temporary directory, for example a `tmpfs` in RAM to minimize writes to the SD card when used on a Raspberry, but system cache in a "permanent" directory, to be available across reboots. Even on a normal PC, you may want to use the HDD for the audio cache and the SSD for system cache to minimize the number of writes on your SSD.
Happy to change anything if needed, this is my first time writing some Rust

Feature split cache folders, resolves #505

---

playback/src/audio_backend/pulseaudio.rs

Fixes #576.
It was the wrong use of `mem::transmute`. Unsafe is dangerous.

Fix playback in pulseaudio backend

---

core/src/spotify_id.rs

This PR picks up the effort made in #459 to refactor SpotifyId. Since @alcore seems not to be interested anymore, I rebased it and applied some minor changes.
As stated in the original PR, the performance increases significantly, but the code is sometimes more complex. It could be discussed whether the uses of `unsafe` or some manual optimizations are worth the speedup if there's another simpler solution that is not too slow.
Is there anything else that has to be done before this PR could get merged?

Refactor SpotifyId

---

Cargo.lock
playback/Cargo.toml

This should resolve #563, but need to see if CI builds it as I don't have an ALSA capable system available to hand right now. Would be good if someone could test to ensure nothing funny is happening with bumped version. /cc @StopMotionCuber

Bump alsa version in playback crate, remove duplicate dependency

---

src/player_event_handler.rs

I'm not sure if this is worth the breaking change, it just turned out be hard to align ENV names in spotifyd. `src/process.rs` to this as naming was not consistent with the enum names. If there is some changelog I assume it would be good to explicitly mention this as beaking change if it is merged.

Align PLAYER_EVENT naming

---

core/src/authentication.rs
core/src/connection/mod.rs
core/src/session.rs
src/main.rs

Fixes #565 
Errors encountered during authenticate() are mapped to a custom error type with an ErrorKind enum (`BadCredentials`, `PremiumAccountRequired`, `Io` (wraps io errors) and `Msg` (generated, used as a default kind to keep unmapped errors readable)) instead of panicking. 
I am not sure how backward compatibility is usually handled here however! I was thinking about adding this error mapping to a new Session::try_connect (not sure about the naming) function, while keeping the same behavior for Session::connect

fix: map authentication errors to a custom error type

---

audio/src/fetch.rs
core/src/cache.rs
playback/src/player.rs

Fixes #591.
If an `VorbisError` occurs while opening a cached file, the cache file will be deleted and the track will be loaded again. 
I also refactored a piece of code above my fix which didn't make sense to me. The warning `<{}> in not available in format {:?}` would never occur, would it?

Handle corrupt cache files

---

Cargo.lock
audio/src/range_set.rs
core/Cargo.toml
core/src/apresolve.rs
core/src/connection/mod.rs
core/src/lib.rs
core/src/proxytunnel.rs
core/tests/connect.rs

Adding a git dependency of a hyper_proxy version with tokio 1.0 support. It is not yet merged, and as far as I see there was no reaction of the maintainer: tafia/hyper-proxy#18.

Proxy support in tokio migration

---

Cargo.lock
core/src/connection/mod.rs
playback/Cargo.toml
playback/src/audio_backend/rodio.rs
playback/src/player.rs

Firstly, this PR fixes two bugs in the playback crate (well, I also introduced them). 
Secondly, `RodioSink` was modified such that it implements `Send` now. The solution spawns an own thread to create the `rodio::OutputStream`. When `RodioSink` is dropped, this thread is notified via a channel and the `OutputStream` is dropped as well. So `RodioSink` doesn't carry the `OutputStream` anymore and is now `Send`. 
I also used this occasion to improve the error handling in the `RodioSink` using `thiserror`, but this should only be the beginning.
If it's ok, I will continue with those relatively small PRs for the tokio migration, so it's easier to follow what I'm doing and easier to contribute.

[Tokio migration] Make RodioSink Send and other improvements

---

Cargo.lock
audio/Cargo.toml
audio/src/decrypt.rs
connect/Cargo.toml
connect/src/discovery.rs
core/Cargo.toml
core/src/authentication.rs
core/src/connection/handshake.rs

{aes, aes-ctr}: 0.3 -> 0.6
sha-1: 0.8 -> 0.9
hmac: 0.7 -> 0.10
{pbkdf2, block-modes}: 0.3 -> 0.7
In those crates were some breaking changes, but I think I figured it out and everything works as before.

Bump crypto crates

---

connect/src/spirc.rs

Fix play/pause toggling in `handle_play_pause()` to correctly call `handle_play()`/`handle_pause()` based on the state.
Currently for both playing and paused states `handle_play()` is called.

Fix state toggling in SpircCommand::PlayPause

---

Cargo.lock
Cargo.toml
connect/Cargo.toml
connect/src/discovery.rs
connect/src/spirc.rs
core/src/mercury/mod.rs
core/src/mercury/sender.rs
core/src/session.rs
playback/src/player.rs
src/lib.rs
src/main.rs
src/player_event_handler.rs

This PR finishes the tokio migration. The application is working again - after all it was easier than I thought -, but I'm pretty sure it's not perfect yet. 
I had to figure out how to make the player blocking again because there were some mysterious bugs in the async version (now it's again unimportant whether the sinks are Send, but it's nice to have).
@sashahilton00 @ashthespy How do we proceed? Before merging it into dev it should be tested more thoroughly, and I would like to do some refactoring.

Finish tokio migration

---

.github/workflows/test.yml
COMPILING.md
Cargo.lock

Attempts to restore the MSRV to 1.41 which is the rustc version in stable Debian.

Set MSRV to 1.41

---

connect/src/spirc.rs
core/build.rs
core/src/config.rs
core/src/connection/mod.rs
core/src/version.rs
src/main.rs

Since a breaking change is coming anyway, we could also replace the `fn`s in the version module by `const`s, which is closer to their actual purpose I think. I removed those strings that weren't used, but they could be added anytime. Removing them would be a breaking change.
Before merging it, the following questions should be answered.
1. Are the names and the documentation ok?
2. Is really every of the used constants necessary?
3. Shouldn't the cargo package version be used somewhere?
4. Is an own module for those five `const`s really necessary?
5. Are there any dependent crates using one of the strings I removed?

Replace version functions by constants

---

audio/src/fetch.rs
audio/src/lewton_decoder.rs
audio/src/lib.rs
audio/src/passthrough_decoder.rs
audio/src/range_set.rs
connect/src/discovery.rs
core/src/apresolve.rs
core/src/authentication.rs
core/src/channel.rs
core/src/diffie_hellman.rs
core/src/mercury/mod.rs
core/src/mercury/sender.rs
core/src/session.rs
core/src/spotify_id.rs
core/tests/connect.rs
metadata/src/lib.rs
playback/src/audio_backend/gstreamer.rs
playback/src/audio_backend/jackaudio.rs
playback/src/audio_backend/mod.rs
playback/src/audio_backend/pulseaudio.rs
playback/src/audio_backend/rodio.rs
playback/src/audio_backend/sdl.rs
playback/src/audio_backend/subprocess.rs
playback/src/mixer/alsamixer.rs
playback/src/player.rs
src/main.rs
src/player_event_handler.rs

I based this off the `tokio_migration` branch since that seems to be the most up to date. When I familiarize myself with a codebase I often go through and clean up little things. I cleaned up:
- the imports (merged & formatted)
- removed stuff from edition 2015 that's no longer needed (extern crate)
- removed last instance of error_chain
- applied lots of clippy lints
- `StreamLoaderController` in audio had methods which didn't need to be `&mut self` anymore
There should be no _real_ code changes here, it's all just cleanups.
There's more I'd like to do but this is already big enough for a PR. I'd like to start removing the `unwrap` and `expect`s in the code. The common practice these days is to use a boxed error type for binary, and `Error` derive (like `thiserror`) on library code. …

clean up imports & clippy lints

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/src/apresolve.rs
core/src/connection/mod.rs
core/src/lib.rs
core/src/proxytunnel.rs
core/src/session.rs

This PR adds back the latest version of hyper-proxy. (It was removed as the migration to tokio was not finished yet). I also restored the old behaviour in some places I believe my refactoring was too eager.
I think it is the last major step before #665 is ready. ~Unfortunately, it is blocked by tafia/hyper-proxy#23.~

[Tokio migration] Add back hyper-proxy

---

audio/src/passthrough_decoder.rs

Per https://github.com/librespot-org/librespot/issues/654 it's probably a better idea to have a separated stream every time the user seeks through the same track. It also makes code simpler and solves the issue with potentially missing BoS. The only case where the EoS might miss is when skipping tracks.

separated stream for each seek

---

playback/src/audio_backend/rodio.rs

Fixed with the recent bump of the Rodio and cpal crates.

Remove warning for Rodio on Alsa (fixed upstream)

---

playback/src/player.rs

b4f9ae31e2832ba6c0bd753eeb36902dd2cb07cc unintentionally broke the basic limiter by testing for equality instead of inequality. In case of the basic limiter, it should confirm that `normalisation_factor <> 1.0` or else don't bother iterating over the samples. This fixes that and slightly changes the `if` statement to better state that intention.

Fix basic normalisation

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/src/cache.rs
playback/src/player.rs
src/main.rs

Limits cache size by calculating the size of the directory on loading of the application and keeping track of additions and removals. As soon as the limit is exceeded, the least recently accessed files are deleted.
Resolves #642.

Add size limit to cache

---

connect/src/spirc.rs

Followed directions [here ](https://github.com/Spotifyd/spotifyd/issues/797) in order to facilitate adding config to spotifyd to configure shuffle mode and have it persist between restarts.

Add shuffle command and command handling

---

.github/workflows/test.yml
COMPILING.md
Cargo.lock
Cargo.toml
connect/Cargo.toml
connect/src/discovery.rs
core/Cargo.toml
core/src/connection/handshake.rs
playback/Cargo.toml

* Applied latest updates of crypto dependencies ~(most notably: the crates aes and aes-ctr were unified)~ but not aes since it requires rust 1.49. 
* I realized that the block-modes dependency wasn't used anywhere so I removed it.
* ~Bumped zerocopy from 0.3 to 0.5.~ (Needs rust version 1.51)
* Update Cargo.lock
* The latest versions of hyper and libmdns require rust 1.46, and sdl requires 1.48, so I bumped the MSRV.
* Adjusted some lower bounds of the version range to match the functionality we use. Unfortunately I was not able to make `rm Cargo.lock && cargo +nightly build -Z minimal-versions` work, but it's a step into the right direction.

Tweak dependencies

---

CHANGELOG.md
CONTRIBUTING.md

Adds a `CHANGELOG.md` file to this repository. The format is based on "Keep a changelog", the link in the file contains more information. 
If this kind of changelog is added, every PR that makes a somewhat bigger change should also update the changelog accordingly. With this policy it should be possible to have a comprehensive changelog for every release.

Add empty changelog

---

Cargo.lock
connect/Cargo.toml
core/Cargo.toml
metadata/Cargo.toml
protocol/Cargo.toml
protocol/build.rs

The version of protobuf was unnecessarily pinned. There were some issues (#460), but e97911e3cfcb85b524e844d0ef5417bbee1e4970 fixed them. It remained pinned only because of the MSRV 1.40 at that time.

Unpin protobuf version

---

.github/dependabot.yml

Currently, dependabot will only check dependencies that are explicitly mentioned in a Cargo.toml file. Therefore, indirect dependencies contained in Cargo.lock will never be updated. This is an attempt to fix it.

Add indirect dependencies to dependabot

---

connect/src/spirc.rs
core/src/connection/handshake.rs
core/src/connection/mod.rs
core/src/mercury/mod.rs
core/src/spotify_id.rs
examples/playlist_tracks.rs
metadata/src/lib.rs
playback/src/player.rs

Fixes the protobuf deprecation warnings (closes #723), and fixes some new clippy warnings.
I disabled the `wrong_self_convention` lint. There are two possible fixes: Rename some functions of `SpotifyId` and `FileId` or remove the `Copy` trait for those structs. 
I would tend to prefer the latter, as they're quite big. 17 bytes and 20 bytes are 3 registers on 64-bit machines and requiring explicit clones wouldn't be that bad. But that's not in the scope of this little PR.
I will merge it right away if the tests pass, @sashahilton00

Fix warnings

---

core/tests/connect.rs

Adds a timeout of 30 secs to the test in `core/tests/connect.rs`. I don't know how often and why this test hangs up, but it happened once in #675.

Add timeout to connection test

---

Cargo.lock
core/Cargo.toml
core/src/apresolve.rs
core/src/connection/mod.rs
core/src/dealer/maps.rs
core/src/dealer/mod.rs
core/src/dealer/protocol.rs
core/src/lib.rs
core/src/session.rs
core/src/socket.rs
core/src/util.rs

(Copied from https://github.com/librespot-org/librespot/discussions/734#discussioncomment-772619)
So, here's my first attempt of websocket support: https://github.com/Johannesd3/librespot/tree/new-api/core/src/dealer
* It uses [tungstenite](https://crates.io/crates/tungstenite) and [tokio-tungstenite](https://crates.io/crates/tokio-tungstenite) as websocket library.
* There's a [`Builder`](https://github.com/Johannesd3/librespot/blob/ad92db0c24f74d0f103ba091b89ce830f9f423a7/core/src/dealer/mod.rs#L116-L194) struct to register handlers before a connection is established.
* After the `Builder` is created, there are two ways to launch the [`Dealer`](https://github.com/Johannesd3/librespot/blob/ad92db0c24f74d0f103ba091b89ce830f9f423a7/core/src/dealer/mod.rs#L253-L312):
* …

Add basic websocket support

---

CHANGELOG.md
connect/src/spirc.rs
core/src/config.rs
playback/src/config.rs
playback/src/mixer/alsamixer.rs
playback/src/mixer/mappings.rs
playback/src/mixer/mod.rs
playback/src/mixer/softmixer.rs
playback/src/player.rs
src/main.rs

Well, what started as a couple of improvements to the log mapping, got me on the road to do a major refactoring of the volume control code after some inspiration by @ashthespy. I think there's quite a bit in here.
**Connect:**
* Move volume computations from `connect` to `playback` crate. For `connect` it's only relevant if there's any sort of volume control so it can enable or disable volume sliders in Connect clients.
* Fix volume step size on volume up/down events. Controlling an official Connect device with an official Connect client, I verified the number of steps (64) to be correct. Likewise the volume range from 0..65535 is correct. The volume step size then needs to be 1024 instead of 4096. The fact that this didn't bit us in the tail before, must be that these events are …

Optimize volume control logic

---

CHANGELOG.md
playback/src/audio_backend/alsa.rs
playback/src/audio_backend/gstreamer.rs
playback/src/audio_backend/pulseaudio.rs
playback/src/convert.rs

No idea if anyone is using `librespot` on big-endian systems, but this makes it so output is always in native endian format. This already was OK on the rest of the backends, and for Alsa it only concerned `S24_3`.

Fix output on big-endian systems

---

Cargo.lock
playback/Cargo.toml
playback/src/convert.rs

This caused quite a bump in CPU usage, which would be acceptable if this actually improved sound quality. However, it turns out that this function only has one decimal precision, i.e. it would consider all values from `0.50..0.60` (exclusive) as `0.5` which is in
error for our purposes.

Revert `math::round_half_to_even`

---

Cargo.toml
core/Cargo.toml
core/src/apresolve.rs
core/src/lib.rs

The feature gate around `apresolve` made it so downstream packages had to opt-in, and always fell back to `ap.spotify.com`. It was enabled by default in `librespot` though.
See: https://github.com/hrkfdn/ncspot/issues/535.

Remove feature gate around `apresolve`

---

Cargo.toml
core/Cargo.toml
core/src/apresolve.rs
core/src/lib.rs
core/src/session.rs

Next to the current access point, the new API has access points for the `dealer` and `spclient` endpoints.
This updates the resolver to fetch those.

Resolve `dealer` and `spclient` access points

---

Cargo.toml
README.md
contrib/librespot.user.service

This new `systemd.service` file allows running and controlling the service as
an unpriviledged user (generally, as part of a user session).
Also document this and the pre-existing service file and how they are used.

Include a systemd.service file to run as a user

---

CHANGELOG.md
playback/Cargo.toml
playback/src/audio_backend/alsa.rs
playback/src/config.rs
playback/src/player.rs

* Create and use meaningful `AlsaError`'s with `thiserror`.
* Remove all usage of `unwrap()` and `expect()` from `alsa.rs`.
* Handle all errors and never `panic!` in `alsa.rs`.
* Remove the use of `std::ffi::CString` by using `HintIter::new_str` instead of `HintIter::new`.
* Consider errors in `sink.start`, `sink.stop` and `sink.write` in `player.rs` as fatal and `exit(1)`.

Better errors alsa backend

---

CHANGELOG.md
playback/src/audio_backend/pipe.rs

* Move all code that can fail to `start` where errors can be returned to prevent a panic!
* Replace unwrap
Another backend fix much the same as the PulseAudio backend fix combined with the ability to gracefully exit on error player in #797 this should about do it for for the whole "never panic!" idea as far as the pipe backend is concerned.

Better errors in pipe backend

---

.github/workflows/test.yml

Let's try just 1 `*`. I'm sorry I'm relying on Google and the github docs so I can't really test this myself very well as CI doesn't run on my fork.

Make CI ignore things that should not trigger build tests (reprise)

---

playback/src/audio_backend/alsa.rs

Doing so on configs that have less than the 4 periods we were asking for caused a crash. Instead ask for a buffer time of 500ms.

Don't explicitly set the number of periods

---

core/src/authentication.rs
discovery/src/server.rs

... to avoid redundant utf-8 checking

Adjust arg types of `Credentials::with_blob`

---

CHANGELOG.md
playback/src/lib.rs

the Sink traits use AudioPacket and Converter and these are currently not public. This prevents you to implement your own sink implementation. I need this to integrate Librespot in my own player

make convert and decoder public as they are needed by Sink traits

---

CHANGELOG.md
playback/Cargo.toml
playback/src/audio_backend/pulseaudio.rs

* Use F32 if a user requests F64 (F64 is not supported by PulseAudio)
* Move all code that can fail to `start` where errors can be returned to prevent a panic!
* Remove unneeded unwraps.
Combined with the ability to gracefully exit on error player in https://github.com/librespot-org/librespot/pull/797 this should about do it for for the whole "never panic!" idea as far as the PulseAudio backend is concerned.

Better errors in PulseAudio backend

---

playback/src/player.rs

This is a small change just to do things right: volume control should be the last in line, after normalisation and potentially other filters. In practice very few if any will notice.
At the same time I removed the clamping of floating point samples. It's not necessary, when converting to integer samples the conversion will saturate at the bounds (i.e. clip) anyway.

Attenuate after normalisation

---

CHANGELOG.md
playback/src/config.rs
src/main.rs

The latest protobufs indicate that Spotify has changed its normalisation threshold from -1 to -2 dBFS.
Spotify also updated its pregain settings, and I already edited the wiki to follow suit.

Update default normalisation threshold

---

CHANGELOG.md
audio/src/fetch/receive.rs
connect/src/spirc.rs
playback/src/config.rs
playback/src/player.rs
src/main.rs

As discussed in #780, this adds an "auto" normalisation type, and makes it the default. This automatically picks the album or track ReplayGain values, depending on whether the current context is an album context or not.
When autoplay is enabled and the playlist is extended when an album reaches its end, then "auto" starts picking the track values until an album is put up again.

Add and default to "auto" normalisation type

---

CHANGELOG.md
playback/Cargo.toml
playback/src/audio_backend/jackaudio.rs
playback/src/audio_backend/portaudio.rs
playback/src/audio_backend/rodio.rs
playback/src/audio_backend/sdl.rs
playback/src/decoder/lewton_decoder.rs
playback/src/decoder/mod.rs
playback/src/decoder/passthrough_decoder.rs
playback/src/lib.rs
playback/src/player.rs

* Make the decoders and player use the same math for converting between samples and milliseconds.
* Remove unwraps, expects and panics from player, decoders and mod.
* Reduce redundant math.
* Simplify decoder errors with thiserror.

Improve player

---

protocol/proto/spotify/login5/v3/credentials/credentials.proto
protocol/proto/spotify/login5/v3/login5.proto

Is there any reason Google sign in credential was excluded from the protobufs? The Google sign in definition was taken from Spotify 1.1.68.

Add Google sign in credential to protobufs

---

playback/src/audio_backend/alsa.rs

Kinda silly in this particular case, but clippy complains that "`if` chain can be rewritten with `match`".

Fix clippy comparison chain warning

---

CHANGELOG.md
src/main.rs

Prevent hang when discovery is disabled and there are no credentials or when bad credentials are given.

Prevent librespot from becoming a zombie

---

CHANGELOG.md
core/src/config.rs
playback/src/audio_backend/mod.rs
playback/src/config.rs
playback/src/mixer/mod.rs
src/main.rs

* Don't panic when parsing options. Instead list valid values and exit.
* Get rid of needless .expect in playback/src/audio_backend/mod.rs.
* Enforce reasonable ranges for option values (breaking).
* Don't evaluate options that would otherwise have no effect.
* Add pub const MIXERS to mixer/mod.rs very similar to the audio_backend's implementation. (non-breaking though)
* Use different option descriptions and error messages based on what backends are enabled at build time.
* Add a -q, --quiet option that changed the logging level to warn.
* Add a short name for every flag and option.
* Note removed options.
* Other misc cleanups.

Refactor main.rs

---

connect/src/spirc.rs

to prevent 'index out of bounds: the len is 0 but the index is 0'
https://github.com/librespot-org/librespot/issues/226#issuecomment-971642037

Guard against tracks_len being zero

---

CHANGELOG.md
playback/src/audio_backend/alsa.rs

This makes `--device ?` only show compatible devices (ones that support 2 ch 44.1 Interleaved) and it shows what `librespot` format(s) they support.
This should be more useful to users as the info maps directly to `librespot`'s `--device` and `--format` options.
The output looks like this:
```
Compatible alsa device(s):
----------------------------------------------
Device:
hw:CARD=Generic,DEV=3
Description:
HD-Audio Generic, HDMI 0
Direct hardware device without any conversions
Supported Format(s):
S32 S16
----------------------------------------------
Device:
hw:CARD=Generic,DEV=7
Description:
HD-Audio Generic, HDMI 1
Direct hardware device without any conversions
Supported Format(s):
S32 S16
----------------------------------------------
Device:
hw:CARD=Generic,DEV=8
Description: …
```

Improve `--device ?` functionality for the alsa backend

---

CHANGELOG.md
contrib/librespot.service
contrib/librespot.user.service

Running as `nobody` throws the following warning:
```
/usr/lib/systemd/system/librespot.service:9: Special user nobody configured, this is not safe!
```
Since it appears librespot doesn't require its own per-say, I've chosen [DynamicUser](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#DynamicUser=), which adds some sand-boxing niceties alongside.
I've also changed the [Restart](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=) policy to `on-failure` as it would otherwise restart on clean/0 exit codes.

Harden systemd service, update restart policy

---

CHANGELOG.md
playback/src/audio_backend/alsa.rs
src/main.rs

* Make librespot able to parse environment variables for options and flags. To avoid name collisions environment variables must be prepended with `LIBRESPOT_` so option/flag `foo-bar` becomes `LIBRESPOT_FOO_BAR`.
* Verbose logging mode (`-v`, `--verbose`, `LIBRESPOT_VERBOSE=`) now logs all parsed environment variables and command line arguments (credentials are redacted).

parse environment variables

---

connect/src/context.rs
core/src/connection/codec.rs
playback/src/audio_backend/jackaudio.rs
playback/src/audio_backend/mod.rs
playback/src/audio_backend/rodio.rs
playback/src/mixer/alsamixer.rs

I noticed this while building Raspotify packages. Let's see if it doesn't trip up rust 1.48?

Address clippy lint warnings for rust 1.57

---

contrib/Dockerfile

Add arm64 target to docker run examples. 
Remove  feature quotes as they're not necessary and don't match
the non-quoted examples of targets in the cross compile section of the  [WIKI](https://github.com/librespot-org/librespot/wiki/Cross-compiling)

Add arm64 target example

---

src/main.rs

Fix Command line arguments incorrectly echoed in TRACE

---

CHANGELOG.md
src/main.rs

As mentioned in https://github.com/librespot-org/librespot/issues/898#issuecomment-986528998
`--alsa-mixer-device` and `--alsa-mixer-index` now fallback to the card and index specified in `--device`.

Fix auto fallback for --alsa-mixer-device and --alsa-mixer-index

---

Cargo.lock
playback/Cargo.toml
playback/src/player.rs

Fix a race where the load operation was trying to use a disposed tokio
context, resulting in panic.

player: ensure load threads are done when dropping PlayerInternal

---

CHANGELOG.md
playback/src/audio_backend/jackaudio.rs
playback/src/audio_backend/mod.rs
playback/src/audio_backend/portaudio.rs
playback/src/audio_backend/rodio.rs
playback/src/audio_backend/sdl.rs
playback/src/player.rs

Prevent a copy if the implementation needs to keep the data around.

Sink: pass ownership of the packet on write()

---

CHANGELOG.md
playback/src/audio_backend/pipe.rs
playback/src/audio_backend/rodio.rs
playback/src/audio_backend/subprocess.rs
src/main.rs

Fixes #936.
This removes the `The ``--{}`` / ``-{}`` option is not supported by the included audio backend(s), and has no effect.` message that was introduced by @JasonLG1979. I couldn't find an easy and maintainable way of implementing this in all backends (like a `fn supports_device() -> bool where Self:: Sized` method in the `Sink` trait) and thought that low code complexity trumps here.
Also some small cleanups and the change that `pipe` now creates a file if it didn't already exist.

Fix `--device` argument to various backends

---

CHANGELOG.md
playback/src/config.rs
playback/src/player.rs
src/main.rs

Well that was a fun exercise! This time I actually think I know what I'm doing.
The current dynamic limiter was an amateur attempt that worked within a limited range and first Rust code I ever wrote. This time I took a article from the Journal of the Audio Engineering Society [1] and wrote a fresh implementation of the most recommended variant (feed-forward in the log domain with a smooth, decoupled peak detector).
So far it seems to work beautifully, including the tracks with wide dynamic range in the linked issue. Would be nice if some of you could give this a spin on various genres and let me know how it goes.
I purposely changed the field names to signal developers downstream that some of these fields now hold values in a different unit. Before in `0.2.0` this caused distorted audio …

New dynamic limiter for very wide dynamic ranges

---

playback/src/config.rs
playback/src/player.rs
src/main.rs

This saves about 5% CPU usage on a Pi Zero and maybe 1-2% on a Pi 4. On anything more powerful than a Pi the diffrence is more than likely imperceivable.

Save some more CPU cycles in the limiter

---

CHANGELOG.md
core/src/cache.rs
core/src/spotify_id.rs
metadata/src/lib.rs
playback/src/player.rs
src/player_event_handler.rs

As mentioned in https://github.com/librespot-org/librespot/discussions/917#discussioncomment-2007452.

Remove unsafe code

---

CHANGELOG.md
playback/src/mixer/alsamixer.rs

When `--volume-range` was set, that propagated to the mapped volume control, but not to the Alsa mixer itself. This caused incorrect `mapped_to_linear` calculations.
Fixes: #948

Fix Alsa softvol linear mapping

---

Cargo.lock
playback/Cargo.toml
playback/src/decoder/symphonia_decoder.rs
playback/src/player.rs

Hello!
This PR updates Symphonia to the newly published v0.5. This release adds gapless playback support (enabled for both Vorbis and MP3), and generally fixes many other quality and/or performance bugs.
I've been running a forked version of librespot with a git version of Symphonia for a couple weeks now and haven't encountered any problems.

Upgrade to Symphonia v0.5.

---

src/main.rs

When there's a value that corresponds to an argument name used in the same command line, the logging of the arguments gets confused and logs the matching argument, but without the leading dash:
```
% target/debug/librespot -n c --verbose -c /path/to/my/cache
[2022-02-07T22:32:25Z INFO  librespot] librespot 0.3.1 55ced49 (Built on 2022-02-07, Build ID: qaEB8kEW, Profile: debug)
[2022-02-07T22:32:25Z TRACE librespot] Command line argument(s):
[2022-02-07T22:32:25Z TRACE librespot] 		-n "c"
[2022-02-07T22:32:25Z TRACE librespot] 		c "/path/to/my/cache"
[2022-02-07T22:32:25Z TRACE librespot] 		--verbose
[2022-02-07T22:32:25Z TRACE librespot] 		-c "/path/to/my/cache"
```
Here we're using the literal `c` as the device name, and the `-c` argument. Thus the `c /path/to/my/cache` is logged in …

Only log runtime argument if it starts with a dash "-"

---

playback/src/convert.rs
playback/src/dither.rs
playback/src/player.rs

* We don't need to test against EPSILON. The factor will never be over 1.0 in basic normalisation mode.
* Don't check the normalisation mode EVERY sample.
* Do as little math as possible by simplfiying all equations as much as possible (while still retaining the textbook equations in comments).
This saves up to 1-2% CPU useage on a PI 4 depending on how much normalisation is actually being done.

Quantum Realm level normalisation optimization

---

core/src/dealer/mod.rs

The `split` variable in `split_uri` only needs to be `mut` for debug builds. The compiler will complain about the unused mut while building a release.

Silence compiler warning

---

CHANGELOG.md
playback/src/audio_backend/pulseaudio.rs
src/main.rs

This sets the name displayed by PulseAudio to `Librespot - Instance Name` if a name is given otherwise `Librespot` (the default name).
`librespot -n "Instance Name"` Results in:
This also sets the correct "role" to "music" as per the docs:
https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/ApplicationProperties/
PA_PROP_MEDIA_ROLE
"This is a property of the actual streamed data, not so much the application"
Roles are used for policies, things like automatically muting a music player when a call comes in and whatnot.
For bonus points this also sets `PULSE_PROP_application.icon_name` to `audio-x-generic` so that we get a nice icon in the PulseAudio settings by our name instead of a missing icon placeholder.

Set the PulseAudio name to match librespot's device name

---

discovery/Cargo.toml

On my machine I'm getting spammed with warnings of this type:
```
[2022-05-19T16:56:38Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.112:5353: type 47 is invalid
[2022-05-19T16:56:45Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.114:5353: type 47 is invalid
[2022-05-19T16:56:45Z WARN  libmdns::fsm] couldn't parse packet from 192.168.178.28:5353: type 47 is invalid
```
This is because some devices in my network use mDNS to talk to each other, broadcasting messages to other mDNS devices like the machine running librespot. But this packet type 47 hasn't been implemented in libmdns, so the warning is printed.
As I use librespot as a systemd daemon all those messages end up in my journal and accumulate to >1000 warning per day. This warning has been fixed 11 days …

Bump libmdns to 0.7

---

examples/play.rs
playback/src/mixer/mod.rs
playback/src/mixer/softmixer.rs
playback/src/player.rs
src/main.rs

Move volume calculations out of their own separate samples iteration and into the normalisation iteration.
I plan on doing this and more in the new API branch. This bit was just a quick and easy backport that really don't change much at all. Further work on the new API branch may get backports or not depending on if/when 0.4 is released, as anything after 0.4 can't break the 0.4 API.

Remove the volume sample iteration

---

CHANGELOG.md
discovery/src/lib.rs
src/main.rs

When librespot is built with Avahi turned on, it will crash if Avahi is
later not available at runtime.
This change avoids it crashing hard when Avahi is not available;
librespot will merely warn of the issue.
This affects some distribution packages too, where the maintainer might
prefer leaving Avahi support enabled, but many setups don't (or can't)
run Avahi.

Avoid crash when Avahi is not available

---

core/build.rs

Allow to override `LIBRESPOT_BUILD_ID` with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
I had an earlier version that used `StdRng::seed_from_u64(val.parse().unwrap())` but thought that the extra complexity would be disadvantageous.
This PR was done while working on reproducible builds for openSUSE.

Allow to override build_id with SOURCE_DATE_EPOCH

---

CHANGELOG.md
core/src/session.rs
core/tests/connect.rs
examples/get_token.rs
examples/play.rs
examples/playlist_tracks.rs
src/main.rs

This adds a callback to the creation of the session, so the reusable credentials can be stored separately. This is useful when using a keychain or something like the secret_service api.
The way it's implemented, no API is broken but the possibility to reuse the credentials is there.
When using librespot without the cache, Spotify will send an email about a new login attempt when using the password credentials, with the long-lived token this does not happen. But I don't want to either use the cache or I don't want the token in a json file on my fs.
Feel free to give me some feedback or another solution, but I’m relatively new to rust, so I might ask some questions.

adding callback for reusable credentials

---

CHANGELOG.md
Cargo.lock
playback/Cargo.toml
playback/src/audio_backend/gstreamer.rs

Should help with #974. Testing indicates this gst cleanup is more stable than before, but new_api branch has its own bugs due to changes elsewhere in librespot. It was mentioned in the issue comments that someone could backport this to dev branch.
As one of the original authors of the gstreamer backend, I felt shameful enough about my initial code that I wanted to send this in to help out.
I haven't tested with old rustc, but apparently the gstreamer crate (and friends) version 0.18 and later moved to Rust 2021, while 0.17 is still targeting Rust 2018... so hopefully the rust version compatibility should be the same as current librespot dev branch. I had to update it slightly to support new functions that were absent in gstreamer crate 0.16.x, but fortunately the new functions are present …

Backport sdroege's gstreamer backend cleanup to dev.

---

playback/src/audio_backend/alsa.rs

Silence a clippy warning and we don't need `std::cmp::min` when `usize` already has `min`.

Minor alsa backend tweaks

---

core/src/cdn_url.rs
core/src/date.rs
metadata/src/playlist/attribute.rs
metadata/src/playlist/item.rs
metadata/src/playlist/list.rs
metadata/src/track.rs

On the `new-api` branch, running the `playlist_tracks` example failed for me on all playlists I tried. (e.g., `spotify:playlist:44PATzOl8NaSihxJQs02h6`)
```
T22:31:02Z ERROR librespot_core::session] could not dispatch command: Service unavailable { error handling Mercury response: MercuryResponse { uri: "hm://pusher/v1/connections/some_random_long_string_dont_know_if_this_is_sensitive", status_code: 200, payload: [] } }
[core/src/spotify_id.rs:151] &src = [ 0, 0, 0, 95, 44, 47, 124, 183, 128, 198, 126, 114, 116, 12, 168, 188, 186, 208, 26, 252, 170, 101, 87, 65 ]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidArgument, error: InvalidId }', examples/playlist_tracks.rs:36:58
note: run with `RUST_BACKTRACE=1` environment variable to display a …
```

Fix playlist metadata fields parsing

---

CHANGELOG.md
core/src/apresolve.rs

Only `ap-gew4.spotify.com` is listed now, but the mechanism allows to add other access points to the blacklist if so necessary in the future.
Fixes #972

Blacklist ap-gew4 access point

---

metadata/src/album.rs
metadata/src/artist.rs
metadata/src/audio/file.rs
metadata/src/availability.rs
metadata/src/content_rating.rs
metadata/src/copyright.rs
metadata/src/episode.rs
metadata/src/external_id.rs
metadata/src/image.rs
metadata/src/playlist/attribute.rs
metadata/src/playlist/item.rs
metadata/src/playlist/list.rs
metadata/src/playlist/operation.rs
metadata/src/playlist/permission.rs
metadata/src/restriction.rs
metadata/src/sale_period.rs
metadata/src/track.rs
metadata/src/video.rs

- Derive `Default` trait for the vec / hashmap wrapper types in `librespot-metadata`
- The wrapped types (`Vec` / `Hashmap`) implement Default, so the wrapper types should as well

Implement Default trait for vec / hashmap wrappers in metadata

---

COMPILING.md
Cargo.toml
audio/Cargo.toml
connect/Cargo.toml
core/Cargo.toml
discovery/Cargo.toml
metadata/Cargo.toml
playback/Cargo.toml
protocol/Cargo.toml

See also: https://github.com/librespot-org/librespot/issues/1033
This adds a nice error message in case the rust-version is too old to compile librespot:
```
$ cargo build --release
error: package `librespot v0.5.0-dev (/home/sqozz/git/librespot)` cannot be built because it requires rustc 1.62.2 or newer, while the currently active rustc version is 1.62.1
```
I tried 1.62.1 which also worked fine (just set it higher before to test the warning itself). It is the lowest rustc version available to me it might be possible 1.61.x works too but I've no way to verify this.

Add minimum rust version

---

metadata/src/artist.rs
metadata/src/track.rs

Based on [this patch](https://github.com/librespot-org/librespot/commit/4f54dc8f5b5b9191899b9159801958cc3e748de9), this exposes some more metadata in the public `struct`s that is sent from Spotify.

include more metadata in track struct

---

metadata/src/artist.rs

- The `AlbumGroups` containing `Vec<Albums>` is not flattened into a single `Albums` since the each contained Albums is a collection of different versions of the same album
- So to get the current version of an album only the first `Album` of each `Albums` in `AlbumGroups` has to be used
- The `portrait_group` in `Biography` is flattened since there is no point in the additional abstraction and it only needs to be implemented once
Please check and verify that I implemented the concepts in the correct way. I tried to reference the implementations of the other metadata types for this

Implement additional metadata for Artist

---

metadata/src/album.rs
metadata/src/artist.rs
metadata/src/audio/file.rs
metadata/src/availability.rs
metadata/src/content_rating.rs
metadata/src/copyright.rs
metadata/src/episode.rs
metadata/src/external_id.rs
metadata/src/image.rs
metadata/src/playlist/attribute.rs
metadata/src/playlist/item.rs
metadata/src/playlist/list.rs
metadata/src/playlist/operation.rs
metadata/src/playlist/permission.rs
metadata/src/restriction.rs
metadata/src/sale_period.rs
metadata/src/track.rs
metadata/src/util.rs
metadata/src/video.rs

- Change the `Deref` implementations for metadata wrapper types to use a
new `impl_deref_wrapped` macro
- The macro implements `Deref` and `DerefMut`

Implement `DerefMut` for wrapper types in metadata

---

core/src/apresolve.rs
src/main.rs

- Fixed resolve function panicking when resolving endpoint type with no AP in the list
- Fixed resolve function *draining* the AccessPoints (removing used APs)
- Fixed fallback APs not being applied when only some of the AP types were missing
- Changed the fallback APs to be SocketAddress instead of unresolved URLs
- Changed resolver URL to be HTTP**S** instead of HTTP

Fix panic in `ApResolver::resolve`

---

examples/playlist_tracks.rs
metadata/src/album.rs
metadata/src/artist.rs
metadata/src/playlist/list.rs

- Change the return type of metadata convenience iter functions to actual iterators instead of allocated collections
- The iterator item type is set to be a reference instead of the actual `SpotifyId` since that is a bit more versatile. Especially if at some point in the Track ids would get replaced by non Copy types like actual Tracks. Something like that was done with `Artists` in #1018 . If this is not desired it will of course be changed

Return iterators instead of collected vecs

---

core/src/spclient.rs

The generated endpoint used the debug printed Option instead of the conatined value. So bascially `"/playlist/v2/playlist/Option(id)"` instead of `"/playlist/v2/playlist/id"`

Fix `SpClient::get_playlist` endpoint generation

---

README.md

Raspotify is not Raspberry Pi specific anymore.

Update raspotify description

---

contrib/docker-build-pi-armv6hf.sh

Since the `.deb` files to be downloaded in the old script do not seem to exist anymore and just pointing to new ones did not work either, I did look around a bit and discovered that the build for armv6hp can by now be greatly simplified.  
The resulting binary has been tested without issues on an original Pi Zero W.

Fix armv6hp Builds (RPI 1 & Zero)

---

contrib/docker-build-pi-armv6hf.sh

Same as #1044 just for `old-api` also. Both resulting binaries (`dev` and `old-api`) have been tested on my original Pi Zero W without issues.

Fix armv6hp Builds (RPI 1 & Zero) for `old-api` also

---

core/src/error.rs
metadata/src/artist.rs

From my observations, `ActivityPeriod` **always** comes in one of the following three compositions:
- `decade`
- `start_year` (open timespan)
- `start_year` + `end_year` (closed timespan)
Thus, it probably makes sense to strongly type those variants into `ActivityPeriod`.
I also added two `debug_assert!`s that make sure that the invariants that I assume are always held up. Alternatively, I could also turn them into normal `assert!`s or handle-able exceptions through `TryFrom`. I went for the current variants, since I think it makes most sense, but I'm open to different perspectives!
I've verified my assumptions with the help of the below program for probably around 1000 different artists, so it should be fine? Some example outputs:
- for `spotify:artist:5WUlDfRSoLAfcVSX1WnrxN`: `known …

strongly type `ActivityPeriod`

---

CHANGELOG.md
connect/src/spirc.rs
contrib/event_handler_example.py
core/src/authentication.rs
core/src/session.rs
examples/play.rs
metadata/src/album.rs
metadata/src/audio/item.rs
metadata/src/audio/mod.rs
metadata/src/episode.rs
metadata/src/error.rs
metadata/src/image.rs
metadata/src/track.rs
playback/src/audio_backend/alsa.rs
playback/src/player.rs
src/main.rs
src/player_event_handler.rs

Special thanks to @eladyn for all of their help and suggestions.
* Add all player events to `player_event_handler.rs`
* Move event handler code to `player_event_handler.rs`
* Add session events
* Clean up and de-noise events and event firing
* Added metadata support via a TrackChanged event
* Add `event_handler_example.py`
* Handle invalid track start positions by just starting the track from the beginning
* Add repeat support to `spirc.rs`
* Add `set_position_ms` and `set_volume` to `spirc.rs`
* Set `PlayStatus` to the correct value when Player is loading to avoid blanking out the controls when `self.play_status` is `LoadingPlay` or `LoadingPause` in `spirc.rs`
* Handle attempts to play local files better by basically ignoring attempts to load them in `handle_remote_update` in `spirc.rs` …

Major Events Overhaul

---

examples/play.rs

Because of the adding of item_type to SpotifyId and its subsequent switch-case sprawl throughout the codebase, from_base62 is not playable by default. These constructors set the item_type to Unknown.
This was annoying to debug when I ran into this issue so I think the example should be fixed :)
Edit: forgot to add the import for SpotifyItemType which is what the second commit is for.

Fix play track item_type in the examples folder

---

examples/play.rs
src/main.rs
src/player_event_handler.rs

Fixes
```
warning: the borrowed expression implements the required traits
--> src/player_event_handler.rs:289:24
|
289 |     match Command::new(&v.remove(0))
|                        ^^^^^^^^^^^^ help: change this to: `v.remove(0)`
|
= note: `#[warn(clippy::needless_borrow)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
warning: use of `.unwrap_or_else(..)` to construct default value
--> src/main.rs:698:33
|
698 |                     let value = matches.opt_str(opt).unwrap_or_else(|| "".to_string());
|                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `matches.opt_str(opt).unwrap_or_default()`
|
= note: `#[warn(clippy::unwrap_or_else_default)]` on by default
= …
```

Fix latest clippy warnings

---

CHANGELOG.md
connect/src/spirc.rs
examples/play_connect.rs

This adds functions that activate (i.e. set 'is active' to true/makes it the active player) and load function to play specific tracks.
I've tried to follow the structure used in the rest of the struct, but if there are any issues I'm more than happy to change.

Add activate and load functions to `Spirc`

---

CHANGELOG.md
metadata/src/playlist/list.rs

I've observed that artist mix playlists are being sent with timestamps measured in microseconds. This causes `Date::from_timestamp_ms` to return an error.
Handled with a simple heuristic that will stop working in about two hundred years.

Handle microsecond timestamps

---

CHANGELOG.md
core/src/spotify_id.rs

The encoded URIs were previously missing a colon between the username and item type.

Fix `NamedSpotifyId::to_uri`

---

playback/Cargo.toml

Fix up of #1135, which [makes CI fail](https://github.com/librespot-org/librespot/actions/runs/4489824468/jobs/7896132422?pr=1129), due to conflicting requirements for `jack-sys`.
Should I run `cargo update` as well, or is that usually done some time before a release?

update jack to match alsa requirement

---

.github/dependabot.yml
.github/workflows/test.yml

Your github actions are quite outdated, thus triggering deprecation warnings when the workflows run.
This PR will
- Update all actions to the latest versions
- Install Dependabot which will create a PR if one of your actions becomes outdated, updating it automatically

Update github actions and add Dependabot

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
core/Cargo.toml
core/src/authentication.rs
playback/Cargo.toml
playback/src/audio_backend/gstreamer.rs
playback/src/decoder/passthrough_decoder.rs
playback/src/decoder/symphonia_decoder.rs
protocol/Cargo.toml

I used `cargo-udeps` from [here](https://github.com/est31/cargo-udeps) to scan for unused dependencies. Two package were removed, `num` and `glob`.
With `cargo upgrades` from [here](https://crates.io/crates/cargo-upgrades) I scanned for upgradable dependencies in the `Cagro.toml` files. I updated them (and regenerated the `Cargo.lock`) execept of
```
librespot-core: /core/Cargo.toml
base64 matches 0.13.1;	latest is 0.21.0
quick-xml matches 0.23.1;	latest is 0.28.1
rsa matches 0.6.1;	latest is 0.8.2
vergen matches 7.5.1;	latest is 8.1.0
librespot-discovery: /discovery/Cargo.toml
base64 matches 0.13.1;	latest is 0.21.0
```
because they require changes to the code beyond my rust knowledge. I tracked them down as far as I could - hopefully someone else can continue here:
- `vergen` does not …

Remove and update dependencies

---

.github/workflows/test.yml

This PR removes the `actions-rs/toolchain` action from the `test.yml`. The respective [repo](https://github.com/actions-rs/toolchain) is unmaintained since 3 years and recent Github changes are not accounted for. This causes actions in all repo using this action to trigger massive warnings.
___
This PR replaces the action with a direct download and run of `rustup`, preserving the wanted profile and toolchain.

Remove actions-rs/toolchain

---

CHANGELOG.md
playback/src/player.rs

I've noticed an issue with my CPU usage on a really low end device while playing music with maximum volume. When volume is equal to 1.0 and normalisation is disabled the first condition failed (as it should) and librespot didn't check whether the normalisation was disabled anymore - it just normalised the song anyway using self.config.normalisation_method.

Respect disabled normalisation with maximum volume

---

.github/workflows/test.yml

Running the test workflow is a time and resource consuming task - the workflow runs between 20 and 40 minutes. Currently, the heavy test (compiling and cross-compiling) run before the lighter linting and format checking. This follows the following reasoning:
> The layering here is as follows, checking in priority from highest to lowest:
However, I think the order should be changed to check formatting and linting first:
1. It's very annoying to wait 40 minutes for the checks to see it failing during the last steps due to a minor formatting error.
2. Reduce computational costs (energy): check formatting takes only seconds, compiling up to 30 minutes. If there is any failure (formatting or compiling) we should fail fast to prevent unnecessary computation. Therefore the "faster" checks should …

Check formatting and linting first on workflow

---

core/src/cdn_url.rs

The CDN URLs list now includes spotifycdn.com which has a different format. It was being erroneously interpreted using the scdn.co format and trying to parse non-digit characters as a timestamp.
It was trying to interpret the entire query string of "https://audio-gm-off.spotifycdn.com/audio/4712bc9e47f7feb4ee3450ef2bb545e1d83c3d54?Expires=1688165560~FullPath~hmac=IIZA28qptl8cuGLq15-SjHKHtLoxzpy_6r_JpAU4MfM=" as a number. 
Maybe it would be better to match on the domain? Or at least catch the `parse()` error and just pretend it's not expiring?

Parse expiry timestamp from spotifycdn.com CDN URLs (Fixes #1182)

---

CHANGELOG.md
connect/src/spirc.rs
examples/play.rs
examples/play_connect.rs
playback/src/mixer/mod.rs
playback/src/player.rs
src/main.rs
src/player_event_handler.rs

Create a single player instance, when librespot starts and keep it running over reconnections. In the current implementation the player is recreated on every reconnection, which causes the output device to be recreated too. This creates a racing condition in Jack, which occasionally causes the output device to be created with a different name. This is an issue especially when using Jack's custom routing. I.e. A different user connects via Spotify Connect and Jack doesn't create the configured audio route because of the name change.

Use a single player instance

---

playback/src/player.rs

Provides a fix to not stop the sink when gapless mode is enabled. See #1213.

feat: do not stop sink in gapless mode, fix #1213.

---

discovery/src/server.rs

Fixes the confusing log message noted in #1106.

discovery::server: fix startup log

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/src/config.rs
core/src/spclient.rs
src/main.rs

Ok, let's try #1227 again but now with more feeling...
`data-encoding` was already a transitive dependency of tungstenite so this changeset strictly reduces the dep set of the project.
I've also added some improved logging and made it easier to spoof the OS type by moving the side effect to a single line in `spclient` and parameterizing the use sites.
I tested the hashcash challenge with `"ios"` and found I could stream music (but there were other complaints about 502 responses to some requests and sometimes my decrepit machine was too slow to solve the challenge).

Cargo replace hex with data-encoding

---

audio/src/fetch/mod.rs
audio/src/fetch/receive.rs
audio/src/lib.rs
playback/src/decoder/symphonia_decoder.rs
playback/src/player.rs

This change collects all those audio fetch parameters that were defined as static constants into a dedicated struct, AudioFetchParams. This struct can be read and set statically, allowing a user of the library to modify those parameters without the need to recompile.

Make audio fetch parameters tunable

---

core/src/version.rs

fix: change spotify version needed in clientoken to use semantic format

---

metadata/src/lyrics.rs

Looks like it's been removed from the JSON returned by Spotify.

lyrics: remove fullscreen_action

---

connect/src/spirc.rs
core/src/cdn_url.rs
core/src/connection/handshake.rs
core/src/connection/mod.rs
core/src/date.rs
core/src/session.rs
core/src/spotify_id.rs
metadata/src/album.rs
metadata/src/artist.rs
metadata/src/availability.rs
metadata/src/episode.rs
metadata/src/image.rs
metadata/src/playlist/annotation.rs
metadata/src/playlist/attribute.rs
metadata/src/playlist/diff.rs
metadata/src/playlist/item.rs
metadata/src/playlist/list.rs
metadata/src/playlist/operation.rs
metadata/src/sale_period.rs
metadata/src/show.rs
metadata/src/track.rs
playback/src/audio_backend/pipe.rs

Fixes a clippy warning that occured in [recent tests](https://github.com/librespot-org/librespot/actions/runs/8401256234/job/23275718451?pr=1269) regarding `map_clone` (https://rust-lang.github.io/rust-clippy/master/index.html#/map_clone) and file creation without explicite defining truncation behavior (https://rust-lang.github.io/rust-clippy/master/index.html#/suspicious_open_options)

Fix clippy warnings

---

core/src/spotify_id.rs

A SpotifyId is expected to be a 128 bits integer and can be parsed from a base 62 or 16 string. However the parsing functions only checked the validity of the characters of the string, but not its length. This could result in integer overflows or the parsing of incorrect strings as Spotify ids.
This commit add some checks to the length of the input string passed to the parse functions, and also checks for integer overflows in case of base62 encoded strings.

Fix SpotifyId base 62 and 16 str decoding

---

contrib/Dockerfile

Fix building Docker image for cross-compilation
* Debian **stretch** packages are now available only from **archive.debian.org**
* Use rust **1.71** - MIPS target demoted to tier 3 at **1.72**
With these changes I have been able to cross-compile the 0.4.2 release for my very old RaspberryPi 1.

Fix building Docker image for cross-compilation

---

Cargo.lock
audio/Cargo.toml
audio/src/fetch/mod.rs
audio/src/fetch/receive.rs
core/Cargo.toml
core/src/apresolve.rs
core/src/error.rs
core/src/http_client.rs
core/src/spclient.rs
discovery/Cargo.toml
discovery/src/lib.rs
discovery/src/server.rs

This PR updates `hyper` to version 1.x. I've tested it on windows with default options. The most notable change is in the discovery server, where the code has changed significantly to accommodate changes in `hyper`. The intent of the code remains the same, and I confirmed that it functions correctly on my devices.
[`hyper-proxy`](https://github.com/tafia/hyper-proxy) is swapped out in favor of a maintained fork, [`hyper-proxy2`](https://github.com/siketyan/hyper-proxy2). I've seen mentions of some alternatives; this appears to be the most stable option.
`hyper-rustls` is updated to version [`0.26.0`](https://github.com/rustls/hyper-rustls/releases/tag/v%2F0.26.0) to get `hyper` 1.x support, but is held short of the latest version, `0.27.2`, due to build environment changes required for …

Update hyper to 1.x

---

contrib/Dockerfile

The changes to the Docker build made for the `old-api` branch in #1289 are also required in the `dev` branch.
Changes cherry-picked from the original commit.
* Debian **stretch** packages are now available only from **archive.debian.org**
* Use rust **1.71** - MIPS target demoted to tier 3 at **1.72**
With these changes I have been able to build the `dev` branch for all architectures **except** MIPS.
Does it still make sense to maintain the MIPS architecture? Are there any known uses of **librespot** on MIPS devices?

Fix building Docker image for cross-compilation [dev branch]

---

contrib/Dockerfile
contrib/docker-build.sh

Follow up to #1297 and #1298
Given that:
- MSRV was moved up to 1.73.
- Even with rust 1.71 the MIPS target did not build successfully.
- Apparently there is hardly any interest in maintaining the MIPS platform.
- Last but not least - the Docker image for cross-compilation did not build - since MIPS target was demoted to tier 3 at 1.72.
I propose to remove the **MIPS** architecture entirely from the Docker image for cross compilation.
After these changes, I was able to:
- Build the Docker image.
- Cross compile for all remaining platforms.
- Verify that **x86_64** and **aarch64** binaries work fine on Ubuntu 22.04 (regular PC) and Raspberry PI OS (64-bit/bookworm/Raspberry Pi 3) respectively.

Docker cross compile - remove MIPS target platform

---

connect/src/config.rs
discovery/examples/discovery_group.rs
discovery/src/lib.rs
discovery/src/server.rs
src/main.rs

This PR adds support for the `groupStatus` flag of the Spotify ZeroConf API and a flag in the CLI to set it.
Motivation:
This allows differentiating between single and group devices when you have multiple Librespot instances or Connect devices on your network.
Notes:
The [ZeroConf docs](https://developer.spotify.com/documentation/commercial-hardware/implementation/guides/zeroconf) show `GROUP` and `NONE` as valid options for `groupStatus`.
There was no obvious short flag to set for the new `group` flag, so no short flag was set.
Verifying:
The new example at `discovery/discovery_group.rs`.
The command `cargo run -- --name "Librespot Group" --group`.
Example:
Let me know if you would like any changes!

add flag to display connect device as group

---

core/src/spclient.rs
core/src/version.rs

Fix spotify version in client token request

---

Cargo.lock
Cargo.toml
discovery/Cargo.toml

Hopefully resolves https://github.com/Spotifyd/spotifyd/issues/1285
Also fixed a cargo toml warning regarding rust 2024 dropping `default_features` in favor of `default-features`

Bump libmdns from 0.8.0 to 0.9.1

---

.cargo/config.toml
.github/workflows/test.yml
.gitignore
Cargo.lock
core/Cargo.toml

Updates `hyper-rustls` > 0.27 changed it's backend to `aws-lc-rs` which requires changes to the [build environment](https://github.com/rustls/hyper-rustls/releases/tag/v%2F0.27.0). 
1) On windows test this was pretty simple, only change was addition of `NASM`
2) The linux cross compilation failed using `cross`. `cross` setups a docker based build environment and despite trying hard I could not get it building the armv7 binary (mainly, because `bindgen` is required to build `aws-lc-rs` which could not be build successful within the container). Therefore, I decided to replace `cross` with native cargo cross-compilation support which is not only faster, easier to debug but also got the binary build easily.

Update hyper-rustls to 0.27 and adjust CI workflow

---

.devcontainer/Dockerfile
.github/workflows/test.yml

Allow [renamed-and-removed-lints](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#renamed-and-removed-lints) for the time being because clippy fails currently for some dependencies warning about 
```
`box_pointers` has been removed: it does not detect other kinds of allocations, and existed only for historical reasons
```
See [here](https://github.com/librespot-org/librespot/actions/runs/10741132401/job/29792281116?pr=1327) for such warnings.

Allow renamed-and-removed-lints

---

CHANGELOG.md
Cargo.toml
core/Cargo.toml
core/src/authentication.rs
core/src/connection/mod.rs
core/src/error.rs
core/src/session.rs
examples/get_token.rs
examples/play.rs
examples/play_connect.rs
examples/playlist_tracks.rs
oauth/Cargo.toml
oauth/examples/oauth.rs
oauth/src/lib.rs
publish.sh
src/lib.rs
src/main.rs

I don't know if this oauth stuff really belongs in core, it doesn't feel quite right there so I added a new module. That new module could be useful standalone so it makes sense. If someone wants to take this and do something else that is fine by me. 
This also leaves the token stuff a bit messy. We now provide two ways to get an access token:
1. `session.token_provider().get_token("your,scopes")` using keymaster (Mercury)
2. `session.spclient().auth_token()` using login5 (HTTP) 
Both methods work (for session auth and playback) when you authenticate your session using a password or stored credentials. However, method 1 doesn't work when you authenticate your session using a spotify token (obtained using either method). 
I think we want to get rid of this annoying pitfall. We could:
a) Get …

Credentials with access token (oauth)

---

.cargo/config.toml
.github/workflows/test.yml
.gitignore

PR https://github.com/librespot-org/librespot/pull/1318 changed the workflow for cross-compiling from `cross` to nativ `cargo`cross compiling. To set the correct linker, `.cargo/config.toml` was used. However, this has unexpected consequences for native builds on armv7 using another compiler. See https://github.com/librespot-org/librespot/commit/78a8c61f8544f57b46788e0458e36210d26b2bdb#commitcomment-146451253
This PR reverts the addition of `.cargo/config.toml` and sets the linker on CI with `CARGO_TARGET_<triple>_LINKER` env.

Remove .cargo/config.toml and set link compiler on CI with CARGO_TARGET_<triple>_LINKER

---

.devcontainer/Dockerfile.alpine
.devcontainer/devcontainer.json
test.sh

This alpine devcontainer saves ~100MB space for the image.
I kept the debian based devcontainer as well - just in case there might be some issues with the musl build. The test suite in `test.sh` runs fine within alpine.

Add alpine based Dockerfile for Devcontainer

---

discovery/src/server.rs

The current active user was almost persisted and reported but wasn't. The handler for the discovery server is under an Arc so I introduced a Mutex to protect the username field and made setting the username and sending the credentials atomic so that every valid credential send corresponds to an active user update.
There doesn't appear currently to be any way for this `activeUser` field to be reset back to the empty string when a user disconnects so one could argue that it's actually more broken now than before as it will keep reporting the last user to connect indefinitely instead of the user with a currently active session.
If you're interested in this fix, I may take a look at clearing the value in the future.
This issue was reported by @TimotheeGerber in …

discovery::server: fix activeUser field of getInfo

---

.github/workflows/test.yml

Adds `aarch64` and `riscv64` cross compilation targets to the test suite.

Add `aarch64` and `riscv64` cross compilation targets to the test suite

---

.devcontainer/Dockerfile
.devcontainer/Dockerfile.alpine
.github/workflows/test.yml
Cargo.lock
connect/Cargo.toml
core/Cargo.toml
metadata/Cargo.toml
protocol/Cargo.toml

Reverts the changes made in https://github.com/librespot-org/librespot/pull/1328.
Protobuff 3.5.1. fixed the underlying issue (https://github.com/stepancheg/rust-protobuf/pull/733). `librespot` already used version `3` of this create, but in the `Cargo.lock` it was set to `3.4.1`. Specifying the minor version of the crate by `3.5` updated the `Cargo.lock` to use `3.5.1`

Revert lint exception by setting minor version of protobuf

---

.github/workflows/test.yml

- Ensure the Cargo.lock file has been updated after changes are made to Cargo.toml.
- Run tests in CI using the exact versions in the lock file.
Exposes https://github.com/librespot-org/librespot/issues/1336

Freeze dependencies used in CI

---

CHANGELOG.md
core/src/connection/mod.rs
core/src/session.rs

When session connection fails, retry the access point. If still fails for a non-auth-login reason, repeat for the other access points. Also some logging tweaks.
When blocking ap-gew1.spotify.com, now I see each a retry for each AP on that host, until it finds an AP on a different host and succeeds.  
```
[2024-09-20T22:41:44Z DEBUG librespot_core::http_client] Requesting https://apresolve.spotify.com/?type=accesspoint&type=dealer&type=spclient
[2024-09-20T22:41:44Z INFO  librespot_core::session] Connecting to AP "ap-gew1.spotify.com:4070"
[2024-09-20T22:41:44Z DEBUG librespot_core::connection] Connection failed: Connection refused (os error 111)
[2024-09-20T22:41:44Z DEBUG librespot_core::connection] Retry access point...
[2024-09-20T22:41:44Z DEBUG librespot_core::connection] Connection …
```

core: retry session connection

---

CHANGELOG.md
core/src/connection/mod.rs

My work network blocks port 4070 and librespot gets stuck indefinitely for me when it tries to use these APs. This allows it to give up after a few seconds and move on to a different port.

core: AP connection attempts have 3 sec timeout.

---

Cargo.lock
playback/Cargo.toml

```
librespot-playback
/workspaces/librespot/playback/Cargo.toml
dependency       current  upgrade
glib             0.19.9   0.20.3
gstreamer        0.22.7   0.23.1
gstreamer-app    0.22.6   0.23.0
gstreamer-audio  0.22.6   0.23.0
```
The upstream [bug](https://github.com/EmbarkStudios/cfg-expr/issues/73) has been fixed. Just need to wait before dependencies pick up the new version and it propagates through the crates.

Update `glib` and `gstreamer`

---

connect/src/spirc.rs

I was compiling `librespot` with the `nightly` toolchain an noticed this warning
```
#10 106.1    Compiling librespot-connect v0.5.0-dev (/librespot/connect)
#10 106.2 warning: elided lifetime has a name
#10 106.2     --> connect/src/spirc.rs:1537:73
#10 106.2      |
#10 106.2 1536 | impl<'a> CommandSender<'a> {
#10 106.2      |      -- lifetime `'a` declared here
#10 106.2 1537 |     fn new(spirc: &'a mut SpircTask, cmd: MessageType) -> CommandSender<'_> {
#10 106.2      |                                                                         ^^ this elided lifetime gets resolved as `'a`
#10 106.2      |
#10 106.2      = note: `#[warn(elided_named_lifetimes)]` on by default
#10 106.2 
#10 106.2 warning: elided lifetime has a name
#10 106.2     --> connect/src/spirc.rs:1552:65
#10 106.2 …
```

Fix elided_named_lifetimes

---

CHANGELOG.md
discovery/src/server.rs

This is meant to address the remaining issues ("touch-up") in #1307, to get the changes ready for inclusion for release.

Exposing service to both IPv4 and IPv6, addressing remaining issues from #

---

contrib/Dockerfile

Fixes docker image's cross compile issues for `arm-unknown-linux-gnueabihf`.
Not sure if changes are desirable upstream, but fixed this for myself and thought that others might find it useful. 
```bash
error: failed to run custom build command for `aws-lc-sys v0.21.2`
Caused by:
process didn't exit successfully: `/build/release/build/aws-lc-sys-d28a1b34df617185/build-script-main` (exit status: 101)
--- stdout
cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
cargo:rerun-if-env-changed=AWS_LC_SYS_INTERNAL_BINDGEN
cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
cargo:rerun-if-env-changed=AWS_LC_SYS_CFLAGS
cargo:rerun-if-env-changed=AWS_LC_SYS_PREBUILT_NASM
cargo:rerun-if-env-changed=AWS_LC_SYS_C_STD …
```

Update cross-compile docker image: `contrib/Dockerfile`

---

Cargo.lock
core/Cargo.toml
core/src/session.rs

Another approach to #1357 using the ideas from https://github.com/librespot-org/librespot/pull/1357#issuecomment-2386938448.
This looks like a big change, but much of it is just moving around code: `fn dispatch` is now a part of `DispatchTask` such that it has access to the fields of `DispatchTask` (namely, the timeout and state of the keepalive state machinery).
This is a little different from @roderickvd's idea: I've kept the `KeepAliveState` enum instead of just the `ping_received` flag, and instead there's only a single `Sleep` future around. The deadline of the latter is modified as required.
EDIT: Split into a few more commits now to make this easier to review. For testing, keep-alive events are logged at `TRACE` level.
Fixes #1340 
Closes #1357

Rework session keep-alive logic v2

---

CHANGELOG.md
connect/src/spirc.rs

Initial device volume shows `0`, which is why the intial volume is not properly set. Mixer-volume shows the correct volume for this case.
Fixes #1325

Fix initial volume showing zero but playing full volume

---

CHANGELOG.md
core/src/config.rs
core/src/connection/handshake.rs
core/src/connection/mod.rs
core/src/http_client.rs
core/src/login5.rs
core/src/spclient.rs
core/src/version.rs

As mentioned in https://github.com/librespot-org/librespot/pull/1344, it is quite a hassle to figure out how to test or adjust librespot to work on other platforms, like on mobile. By moving the `OS` constant and the `os_version` into `config.rs` we have a single location where we can adjust these values and mock the different platforms.
I'm unsure if a changelog entry is necessary or would make sense for this change, so i didn't create one yet.

Easier mocking of platforms

---

CHANGELOG.md
core/src/token.rs

Fixes https://github.com/librespot-org/librespot/issues/1331
This PR fixes the issue for getting a token error when providing a specific combination of scopes and client_id. A new function `get_token_with_client_id()` was added to be able to provide a specific client_id when asking for a token. 
The original `get_token()` function was kept in order to be fully backward compatible and not break any get_token() function call (for v0.5.0 and dev).

Get token with client

---

CHANGELOG.md
Cargo.lock
core/Cargo.toml
core/src/http_client.rs

Automatically choose to use `rustls-webpki` if the platform doesn't support `rustls-native-certs` (ie: non-desktop platforms).
Main motivation is `rustls-native-certs` is not supported by all platforms, and therefore HTTPs calls will error with 0 native roots
Partially fixes: #1399

feat: use webpki as rustls roots on non-desktop platforms

---

CHANGELOG.md
core/src/connection/handshake.rs
core/src/connection/mod.rs
core/src/login5.rs

Fixes: #1399 
I have mostly figured out the nuances and rules to get streaming on Android to work again.
1. If we send `client_hello` that has `platform == Platform::PLATFORM_ANDROID_ARM`, it does not matter what credentials we send to the AP, all APs will error with `TryAnotherAP`, tested true for credentials obtained via
- oauth flow access_token with Keymaster client ID, requesting `streaming` scope (Credentials::with_access_token)
- oauth flow access_token with Android client ID, requesting `streaming` scope (Credentials::with_access_token)
- login5 flow with Android client ID
```rs
let credentials = Credentials {
username: Some(id),
auth_type: AuthenticationType::AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS,
auth_data, // stored_credentials from Login5Manager::login
};
```
Therefore the …

fix: streaming on Android devices

---

CHANGELOG.md
connect/src/model.rs
connect/src/spirc.rs
core/src/dealer/protocol/request.rs

Fix 'play' command requiring 'offset' field

---

CHANGELOG.md
connect/src/spirc.rs
core/src/session.rs

Disconnecting now only handles disconnecting and not pausing/stopping. But because it feels unnatural to call disconnect on the `Spirc` and not having the player pause, the method now provides an additional option to explicitly pause.
improves the behavior in #1419 but doesn't fix it

Dealer: Improve disconnect

---

CHANGELOG.md
discovery/src/lib.rs

Small improvement to discovery error handling (in fact, with the design of the code with an `inner` method which allows using the `?` operator, I suspect this was the intended code in the first place). Partially fixes #1404 by yielding the error to the main task, which can exit librespot an in turn give the service manager a chance to restart.
In detail: On panic, the discovery task crashes, but the main program is not notified of this. Returning an error will result in the Discovery stream yielding None, serving as notification to the application (which might shutdown with error, for example, if no other means of authentication is available).

discovery: don't panic on libmdns errors

---

.devcontainer/Dockerfile
.devcontainer/Dockerfile.alpine
.github/workflows/test.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
contrib/Dockerfile
discovery/Cargo.toml
discovery/src/avahi.rs
playback/Cargo.toml
playback/src/audio_backend/jackaudio.rs

The alternative fix to #1425.
I settled for 1.81 as MSRV, as it solves our CI issue and provides additional options to update our dependencies, which couldn't be updated before by @yubiuser. This version is currently two behind stable.

Update MSRV to 1.81

---

CHANGELOG.md
metadata/src/show.rs

I stumbled across a show, which has an empty `trailer_uri`. In particular, the `trailer_uri` field on the `librespot_protocol::metadata::Show` struct was `Some("")`, which led to the `SpotifyId::from_uri` parsing to fail.
This patch accounts for this possibility. Another option would of course be to just use `String` for that field, to avoid any parsing problems.
<details><summary>Example:</summary>
previously, doing `Show::get(&session, &id).await` yielded for `spotify:show:28sR8OiOq0MMnGEzMJTXSt`:
```
Error { kind: InvalidArgument, error: InvalidFormat }
```
With this, it returns:
```
Show {
id: SpotifyId(
"spotify:show:28sR8OiOq0MMnGEzMJTXSt",
),
name: "1,5 Grad – der Klima-Podcast mit Luisa Neubauer",
description: "Die Klimakrise ist hier. Wir haben alle Fakten, die wir brauchen, um …
```

metadata: handle empty trailer_uri for shows

---

CHANGELOG.md
connect/src/state/context.rs

Fixes #1438 
The `uri` field of `ContextTrack` protobuf message was an empty string in my case.
The pattern matching here accepted only `None` so did not try to get the track by `gid`.
Once we reach this final matcher, `uri` is either `None` or an empty string so this should not cause any issues.

Handle 'None' uri or empty string uri in transfer command

---

CHANGELOG.md
connect/src/spirc.rs

The play/paused state was inverted. So if we were playing something it would not resume after loading.
`is_paused()` defaults to `false` if `None`, so by default it plays. Not sure if that's correct behavior, I guess the field being called `is_paused` seems to imply that playing is the default state.

Fix pause state when transferring playback

---

contrib/Dockerfile

Changes Shrink the resulting image with 70mb by removing unused dependencies and merging several
runs to a single layer.

Shrink/Optimize Dockerfile

---

.github/workflows/test.yml
CHANGELOG.md

Downgrade bindgen version to 0.70.1 to fix test cases. New bindgen versions break cross build

Fix testcases for cross compilation

---

connect/src/state.rs

With the dealer rework I removed `has_volume_ctrl`, but it seems there are use cases in production (see https://github.com/Spotifyd/spotifyd/pull/1317#discussion_r1921273097).
This reintroduces `has_volume_ctrl` as `disable_volume` (aka inverted usage). In addition some new option from the protobuf update are now initialized.

Reintroduce `disable_volume` as connect device option

---

CHANGELOG.md
connect/src/model.rs
connect/src/spirc.rs
examples/play_connect.rs

It only makes sense to directly expose the `autoplay` option to start playing a radio/station. This doesn't start the "radio"-playlist currently found in the spotify UI and rather just switches into the endless autoplay mode.
Previously mentioned here: https://github.com/hrkfdn/ncspot/issues/193

Expose `autoplay` option to `SpircLoadCommand`

---

connect/src/state/tracks.rs

When drag and dropping the currently played track into the "Next from: ..." or Queued item section, it is only send as an empty item with an uri. So it seems we need to add the uri of the current track to these provided tracks.

Handle drag and drop of current track

---

Cargo.lock
playback/Cargo.toml
playback/src/mixer/softmixer.rs

MIPS and MIPSEL [and PowerPC (?)] don't support AtomicU64, since they are 32 bit. However, there is a crate that provides shims for these platforms. When it detects it is running on unsupported platforms, it fallbacks to the shim implementation, using crossbeam Mutex. For supported platforms, there should be no change.
See initial discussion in https://github.com/librespot-org/librespot/issues/1460

Update softmixer.rs to use AtomicU64 from atomic_shim, so that librespot works with MIPS and MIPSEL

---

connect/Cargo.toml
connect/src/context_resolver.rs
connect/src/lib.rs
connect/src/shuffle_vec.rs
connect/src/spirc.rs
connect/src/state.rs
connect/src/state/context.rs
connect/src/state/handle.rs
connect/src/state/metadata.rs
connect/src/state/options.rs
connect/src/state/tracks.rs
connect/src/state/transfer.rs

Follow up on https://github.com/librespot-org/librespot/pull/1356#issuecomment-2427617758
- removes duplication of context tracks when shuffling
- shuffle by a given seed, by that we can restore the shuffle state after a spontaneously disconnect
With the updated protobuf definitions, there is technically a given seed from the side of spotify when transfering playback. The given seed seems to be a hex value which we can convert into a u64 (which we currently use as seed value). But the shuffled queue isn't even similar to what spotify shuffles (which makes sense as they use a more preference base algorithm with less randomness). So when transferring we reshuffle unless we have a previous shuffle seed in the context metadata.

Shuffle tracks in place

---

contrib/Dockerfile
contrib/cross-compile-armv6hf/Dockerfile
contrib/cross-compile-armv6hf/docker-build.sh
contrib/docker-build.sh
core/Cargo.toml

The Docker image intended to cross-compile librespot for armv6hf (i.e. Raspberry Pi 1) did not work for some time.
Changes proposed here attempt to fix this:
- ~~Commit https://github.com/librespot-org/librespot/commit/faeaf506d64ab988d6cc950b58dbe22c0eed9386 changes the default tls library from **aws-lc-rs** to **ring** as suggested by @kingosticks in #1382 (commit: https://github.com/kingosticks/librespot/commit/24bbc6314c991c64d1846162f739f223c44e5779). I tried to compile **aws-lc-rs** for armv6hf, but did not succeed. :disappointed: I understand that this change might be controversial - I am open to discuss this.~~ Reverted in https://github.com/librespot-org/librespot/pull/1457/commits/6bb009af83ac737c60c99efbf5d8598f6debd3d8
- Commit …

Fix cross compilation for armv6hf (Raspberry Pi 1)

---

Cargo.lock
playback/Cargo.toml
playback/src/mixer/softmixer.rs

Replacing atomic_shim with portable-atomic, since atomic_shim worsk well for MIPS and MIPSEL, but has problems with some ARM flavours.

Replacing atomic_shim with portable-atomic

---

CHANGELOG.md
core/src/config.rs
src/main.rs

removes homething devicetype

---

connect/src/spirc.rs
connect/src/state/handle.rs

This should emit the shuffle and repeat event again, when shuffling or repeating changes.
Fixes #1435

Emit shuffle and repeat events again

---

CHANGELOG.md
playback/src/decoder/symphonia_decoder.rs
playback/src/player.rs

The fix prevents seeking past the end of a track by capping the requested seek position to the actual duration. It also makes timestamp calculation more robust.
This does not entirely fix #1472, but does make the decoder more robust against invalid calls.
Please test this for me, because I no longer have a Spotify account.

Saturate seek position to track duration

---

CHANGELOG.md
connect/src/spirc.rs
connect/src/state.rs
src/main.rs

Allow the volume control steps to be configured via the `--volume-steps` command line parameter. The author personally found the default volume steps of `1024` to be completely unusable, and is presently using `128` as his configuration. Updated the default to `64` which more closely mirrors the official client behavior.
Additionally, reduce the delay in volume update from a wopping two seconds to 500ms, again for usability.
Also clean up the seemingly unnecessary use of a pattern match on whether or not `--initial-volume` was supplied.

spirc: Configurable volume control steps

---

CHANGELOG.md
playback/src/config.rs
playback/src/player.rs
src/main.rs
src/player_event_handler.rs

Fixing #1493 
Hey there, I did an example implementation how the playback position could be sent to the user of the Player struct.
The change should be backward compatible and I did throttle the sending of events by only informing every 250ms.
Please tell me in case you prefer a different solution or would like to change something else.

Send playback position as player event

---

connect/src/spirc.rs
core/src/dealer/mod.rs
core/src/dealer/protocol.rs
core/src/deserialize_with.rs

The parsing error was multiple times falsely refereed to as possible cause, even tho it is completely unrelated to the main issue in most cases. 
The issue will always happens when playing from an official player and then transferring the playback to `librespot`. The log message looked like the following:
```
[2025-04-20T09:14:08Z ERROR librespot_connect::spirc] could not parse session_update: Invalid state { Unknown enum variant name: WIFI_BROADCAST_CHANGED at 1:11 }
```
This change reduces the log level for the parsing failure for `session_update` to `warn`, while adding an additional message to highlight why it is only a warning.

Mark unrelated parsing error as warning

---

core/src/mercury/types.rs
core/src/proxytunnel.rs
discovery/src/lib.rs
oauth/src/lib.rs
playback/src/mixer/mappings.rs
src/main.rs

Fixes the current `clippy` warnings and upcoming `clippy` warnings ( up until 1.79, aka current nightly). The fixes where applied automatically by `clippy` with the following commands.
```sh
cargo clippy --workspace --all-features --allow-dirty --fix
```
```sh
cargo +nightly clippy --workspace --all-features --allow-dirty --fix
```

Chore: fix clippy warnings for stable (1.87) and nightly (1.89)

---

CHANGELOG.md
connect/README.md
examples/play_connect.rs
playback/src/mixer/alsamixer.rs
playback/src/mixer/mod.rs
playback/src/mixer/softmixer.rs
src/main.rs

This should address the possible panic found in #1478 by exposing the errors that might occur while opening a device. 
The binary will now exit when it encounters an issue while opening the mixer.
Fixes #1478

Expose possible mixer opening errors

---

CHANGELOG.md
audio/src/fetch/mod.rs
core/src/cdn_url.rs
core/src/spclient.rs

- The solution here is to make `CdnUrl` return all non-expired URLs instead of just the first one. Then, in `AudioFileStreaming` all URLs are tried and the first working URL is selected for later use.
- This means that the fallback logic is not implemented for following requests in `AudioFileFetch::download_range`, but that is also a synchronous function so implementing that would probably require an overhaul of the codebase anyway, unless I'm missing something.
- This would only become an issue if the URL that worked for the first request stopped working for the following requests.
- I tried minimizing API breakage, but it seems impossible to implement the fallback logic inside `stream_from_cdn`, as it is not async (it doesn't actually send the request), so I made it accept the singular …

fix: add fallback logic for CDN urls

---

CHANGELOG.md
playback/src/player.rs

Previously, the normalizer integrator and peak were recalculated as if the samples were a mono stream. If actually *one* channel required limiting and the other not, this could cause nervousness in the stereo imaging.
This PR changes the normalizer to:
- calculate the integrator and peak for each channel individually
- then couple the left/right channel by using the limit gain of each interleaved pair of samples
- be faster by optimizing the hot code path and reducing the number of branches
Again, please test this for me as I don't have a Spotify account anymore. I ported it from [pleezer](https://github.com/roderickvd/pleezer/blob/main/src/normalize.rs) with my permission.
My "go to" track to test limiting is "Blumine" by Mahler on "Masterpieces in Miniature".

Normalizer stereo imaging and performance improvements

---

playback/src/audio_backend/rodio.rs

Motivation for this change is to avoid the `stderr` logs messing up my TUI application

disable logging on rodio stream drop

---

CHANGELOG.md
core/src/spclient.rs

Instead of setting the header later I overwrite the headers in a loop. `insert` seems to replace the existing keys, so the headers given from the outside are still prioritized, and headers set in the builder are not removed.
Fixes #1551

Fix: Fixup how the headers are set in `spclient` to prevent deleting headers

---

CHANGELOG.md
connect/src/spirc.rs

In #1551 @samcook encountered an unexpected behavior during reconnecting.
The issue happens because the reconnect is initiated via zeroconf instead of using the connect interface, aka in the disconnect handling was a major issue where the state itself was deleted. This should only happen when shutting down the dealer so that the dealer can still receive requests and updates.

Fix: Delete the connect state only on spirc shutdown

---

.gitignore
CHANGELOG.md
connect/src/context_resolver.rs
connect/src/shuffle_vec.rs
connect/src/spirc.rs
connect/src/state.rs
connect/src/state/context.rs
connect/src/state/handle.rs
connect/src/state/metadata.rs
connect/src/state/options.rs
connect/src/state/restrictions.rs
connect/src/state/tracks.rs
connect/src/state/transfer.rs

This should allow to combine repeat and shuffle without any odd behaviors. Shuffling itself was quite a bit inconsistent before, so I had to adjust the shuffling a bit so that's a bit more predictable to work with.
@aome510 could you give this a try and see if there is anything weird in the combination or how the queue behaves? Thanks in advance :)
Fixes #1550

Adjust: Allow repeat in combination with shuffle
